.TH "netsnmp_handler_registration_s" 3 "11 Sep 2007" "Version 5.3.2.pre1" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netsnmp_handler_registration_s \- Root registration info.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <agent_handler.h>\fP
.PP
.SH "Detailed Description"
.PP 
Root registration info. 

The variables handlerName, contextName, and rootoid need to be allocated on the heap, when the registration structure is unregistered using \fBunregister_mib_context()\fP the code attempts to free them. 

.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
