.TH "todo" 3 "6 May 2005" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List
 
.IP "\fBGlobal \fBnetsnmp_register_auto_data_table\fP(netsnmp_table_data_set *table_set, char *registration_name) \fP" 1c
create a properly free'ing registeration pointer for the datalist, and get the datalist freed at shutdown. 
.PP

