.TH "netsnmp_column_info_t" 3 "19 Mar 2004" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netsnmp_column_info_t \- column info struct. 
.SH SYNOPSIS
.br
.PP
\fC#include <table.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned short \fBlist_count\fP"
.br
.RI "\fIonly useful if isRange == 0\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
column info struct.
.PP
OVERLAPPING RANGES ARE NOT SUPPORTED. 
.PP
Definition at line 52 of file table.h.
.SH "FIELD DOCUMENTATION"
.PP 
.SS "unsigned short netsnmp_column_info_t::list_count"
.PP
only useful if isRange == 0
.PP
Definition at line 55 of file table.h.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
