.TH "iterator_info_s" 3 "11 Sep 2007" "Version 5.3.2.pre1" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iterator_info_s \- Holds iterator information containing functions which should be called by the iterator_handler to loop over your data set and sort it in a SNMP specific manner.  

.PP
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Holds iterator information containing functions which should be called by the iterator_handler to loop over your data set and sort it in a SNMP specific manner. 

The \fBiterator_info\fP typedef can be used instead of directly calling this struct if you would prefer. 

.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
