.TH "netsnmp_mib_handler_methods" 3 "23 Sep 2009" "Version 5.5" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netsnmp_mib_handler_methods \- 
.PP
Defines the subhandlers to be called by the multiplexer helper.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiplexer.h>\fP
.SH "Detailed Description"
.PP 
Defines the subhandlers to be called by the multiplexer helper. 

.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
