Maintain a registry of MIB subtrees, together with related information regarding mibmodule, sessions, etc
NAME
Maintain a registry of MIB subtrees, together with related information regarding mibmodule, sessions, etc -
Data Structures
struct lookup_cache_context_s
struct lookup_cache_s
Functions
void netsnmp_set_lookup_cache_size (int newsize)
set the lookup cache size for optimized agent registration performance.
int netsnmp_get_lookup_cache_size (void)
retrieves the current value of the lookup cache size
int unregister_mib_context (oid *name, size_t len, int priority, int range_subid, oid range_ubound, const char *context)
Unregisters an OID that has an associated context name value.
int netsnmp_acm_check_subtree (netsnmp_pdu *pdu, oid *name, size_t namelen)
checks to see if everything within a given subtree is either: in view, not in view, or possibly both.
FUNCTION DOCUMENTATION
int netsnmp_acm_check_subtree (netsnmp_pdu * pdu, oid * name, size_t namelen)
checks to see if everything within a given subtree is either: in view, not in view, or possibly both.
If the entire subtree is not-in-view we can use this information to skip calling the sub-handlers entirely.
Returns:
0 if entire subtree is accessible, 5 if not and 7 if portions are both. 1 on error (illegal pdu version).
Definition at line 1194 of file agent_registry.c.
References snmp_pdu::flags, snmp_call_callbacks(), and snmp_pdu::version.
int netsnmp_get_lookup_cache_size (void)
retrieves the current value of the lookup cache size
Returns:
the current lookup cache size
Definition at line 1263 of file agent_registry.c.
Referenced by unregister_mib_context().
void netsnmp_set_lookup_cache_size (int newsize)
set the lookup cache size for optimized agent registration performance.
Parameters:
newsize
set to the maximum size of a cache for a given context. Set to 0 to completely disable caching, or to -1 to set to the default cache size (8), or to a number of your chosing. The rough guide is that it should be equal to the maximum number of simultanious managers you expect to talk to the agent (M) times 80% (or so, he says randomly) the average number (N) of varbinds you expect to receive in a given request for a manager. ie, M times N. Bigger does NOT necessarily mean better. Certainly 16 should be an upper limit. 32 is the hard coded limit.
Definition at line 1250 of file agent_registry.c.
References netsnmp_set_lookup_cache_size().
Referenced by netsnmp_set_lookup_cache_size(), and unregister_mib_context().
int unregister_mib_context (oid * name, size_t len, int priority, int range_subid, oid range_ubound, const char * context)
Unregisters an OID that has an associated context name value.
Typically used when a module has multiple contexts defined. The parameters priority, range_subid, and range_ubound should be used in conjunction with agentx, see RFC 2741, otherwise these values should always be 0.
Parameters:
name
the specific OID to unregister if it conatins the associated context.
len
the length of the OID, use OID_LENGTH macro.
priority
a value between 1 and 255, used to achieve a desired configuration when different sessions register identical or overlapping regions. Subagents with no particular knowledge of priority should register with the default value of 127.
range_subid
permits specifying a range in place of one of a subtree sub-identifiers. When this value is zero, no range is being specified.
range_ubound
the upper bound of a sub-identifier's range. This field is present only if range_subid is not 0.
context
a context name that has been created
Returns:
Definition at line 885 of file agent_registry.c.
References netsnmp_get_lookup_cache_size(), netsnmp_oid_equals(), netsnmp_set_lookup_cache_size(), and snmp_call_callbacks().