.TH "variable_list" 3 "Thu Dec 8 2016" "Version 5.4.3.pre1" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
variable_list \- The netsnmp variable list binding structure, it's typedef'd to netsnmp_variable_list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <snmp_api\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBvariable_list\fP * \fBnext_variable\fP"
.br
.RI "\fINULL for last variable\&. \fP"
.ti -1c
.RI "oid * \fBname\fP"
.br
.RI "\fIObject identifier of variable\&. \fP"
.ti -1c
.RI "size_t \fBname_length\fP"
.br
.RI "\fInumber of subid's in name \fP"
.ti -1c
.RI "u_char \fBtype\fP"
.br
.RI "\fIASN type of variable\&. \fP"
.ti -1c
.RI "\fBnetsnmp_vardata\fP \fBval\fP"
.br
.RI "\fIvalue of variable \fP"
.ti -1c
.RI "size_t \fBval_len\fP"
.br
.RI "\fIthe length of the value to be copied into buf \fP"
.ti -1c
.RI "oid \fBname_loc\fP [MAX_OID_LEN]"
.br
.RI "\fIbuffer to hold the OID \fP"
.ti -1c
.RI "u_char \fBbuf\fP [40]"
.br
.RI "\fI90 percentile < 40\&. \fP"
.ti -1c
.RI "void * \fBdata\fP"
.br
.RI "\fI(Opaque) hook for additional data \fP"
.ti -1c
.RI "void(* \fBdataFreeHook\fP )(void *)"
.br
.RI "\fIcallback to free above \fP"
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The netsnmp variable list binding structure, it's typedef'd to netsnmp_variable_list\&. 
.PP
\fBExamples: \fP
.in +1c
\fBnotification\&.c\fP\&.
.PP
Definition at line 529 of file snmp_api\&.h\&.
.SH "Field Documentation"
.PP 
.SS "u_char variable_list::buf[40]"

.PP
90 percentile < 40\&. 
.PP
Definition at line 545 of file snmp_api\&.h\&.
.SS "void* variable_list::data"

.PP
(Opaque) hook for additional data 
.PP
Definition at line 547 of file snmp_api\&.h\&.
.SS "void(* variable_list::dataFreeHook) (void *)"

.PP
callback to free above 
.PP
Definition at line 549 of file snmp_api\&.h\&.
.SS "oid* variable_list::name"

.PP
Object identifier of variable\&. 
.PP
Definition at line 533 of file snmp_api\&.h\&.
.SS "size_t variable_list::name_length"

.PP
number of subid's in name 
.PP
Definition at line 535 of file snmp_api\&.h\&.
.SS "oid variable_list::name_loc[MAX_OID_LEN]"

.PP
buffer to hold the OID 
.PP
Definition at line 543 of file snmp_api\&.h\&.
.SS "struct \fBvariable_list\fP* variable_list::next_variable"

.PP
NULL for last variable\&. 
.PP
Definition at line 531 of file snmp_api\&.h\&.
.SS "u_char variable_list::type"

.PP
ASN type of variable\&. 
.PP
\fBExamples: \fP
.in +1c
\fBdelayed_instance\&.c\fP\&.
.PP
Definition at line 537 of file snmp_api\&.h\&.
.SS "\fBnetsnmp_vardata\fP variable_list::val"

.PP
value of variable 
.PP
\fBExamples: \fP
.in +1c
\fBdelayed_instance\&.c\fP\&.
.PP
Definition at line 539 of file snmp_api\&.h\&.
.SS "size_t variable_list::val_len"

.PP
the length of the value to be copied into buf 
.PP
Definition at line 541 of file snmp_api\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code\&.
