.TH "todo" 3 "16 Jul 2004" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List
 
.IP "\fBGlobal \fBnetsnmp_add_varbind_to_cache\fP(netsnmp_agent_session *asp, int vbcount, netsnmp_variable_list *varbind_ptr, netsnmp_subtree *tp) \fP" 1c
make this be more intelligent about ranges. Right now we merely take the highest level commonality of a registration range and use that. At times we might be able to be smarter about checking the range itself as opposed to the node above where the range exists, but I doubt this will come up all that frequently.
.PP
.PP
 
.IP "\fBGlobal \fBnetsnmp_read_data_callback\fP(const char *token, char *line) \fP" 1c
make netsnmp_read_data_callback deal with a free routine
.PP
.PP
 
.IP "\fBGlobal \fBnetsnmp_register_save_list\fP(netsnmp_data_list **datalist, const char *type, const char *token, Netsnmp_Save_List_Data *data_list_save_ptr, Netsnmp_Read_List_Data *data_list_read_ptr, Netsnmp_Free_List_Data *data_list_free_ptr) \fP" 1c
netsnmp_register_save_list should handle the same token name being saved from different types?
.PP
.PP
 
.IP "\fBGlobal \fBnetsnmp_register_auto_data_table\fP(netsnmp_table_data_set *table_set, char *registration_name) \fP" 1c
create a properly free'ing registeration pointer for the datalist, and get the datalist freed at shutdown. 
.PP

