.TH "netsnmp_request_info_s" 3 "23 Sep 2009" "Version 5.5" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netsnmp_request_info_s \- 
.PP
The netsnmp request info structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <snmp_agent.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBnetsnmp_variable_list\fP * \fBrequestvb\fP"
.br
.RI "\fI\fBvariable\fP bindings \fP"
.ti -1c
.RI "\fBnetsnmp_data_list\fP * \fBparent_data\fP"
.br
.RI "\fIcan be used to pass information on a per-request basis from a helper to the later handlers \fP"
.ti -1c
.RI "struct \fBnetsnmp_agent_request_info_s\fP * \fBagent_req_info\fP"
.br
.ti -1c
.RI "oid * \fBrange_end\fP"
.br
.RI "\fIdon't free, reference to (struct \fBtree\fP)->end \fP"
.ti -1c
.RI "size_t \fBrange_end_len\fP"
.br
.ti -1c
.RI "int \fBdelegated\fP"
.br
.ti -1c
.RI "int \fBprocessed\fP"
.br
.ti -1c
.RI "int \fBinclusive\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.RI "\fIindex in original pdu \fP"
.ti -1c
.RI "int \fBrepeat\fP"
.br
.RI "\fIget-bulk \fP"
.ti -1c
.RI "int \fBorig_repeat\fP"
.br
.ti -1c
.RI "\fBnetsnmp_variable_list\fP * \fBrequestvb_start\fP"
.br
.ti -1c
.RI "struct \fBnetsnmp_request_info_s\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBnetsnmp_request_info_s\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBnetsnmp_subtree_s\fP * \fBsubtree\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The netsnmp request info structure. 
.PP
\fBExamples: \fP
.in +1c
.PP
\fBdelayed_instance.c\fP.
.PP
Definition at line 54 of file snmp_agent.h.
.SH "Field Documentation"
.PP 
.SS "int \fBnetsnmp_request_info_s::index\fP"
.PP
index in original pdu 
.PP
Definition at line 84 of file snmp_agent.h.
.SS "\fBnetsnmp_data_list\fP* \fBnetsnmp_request_info_s::parent_data\fP"
.PP
can be used to pass information on a per-request basis from a helper to the later handlers 
.PP
Definition at line 64 of file snmp_agent.h.
.SS "oid* \fBnetsnmp_request_info_s::range_end\fP"
.PP
don't free, reference to (struct \fBtree\fP)->end 
.PP
Definition at line 72 of file snmp_agent.h.
.SS "int \fBnetsnmp_request_info_s::repeat\fP"
.PP
get-bulk 
.PP
Definition at line 87 of file snmp_agent.h.
.SS "\fBnetsnmp_variable_list\fP* \fBnetsnmp_request_info_s::requestvb\fP"
.PP
\fBvariable\fP bindings 
.PP
\fBExamples: \fP
.in +1c
\fBdelayed_instance.c\fP.
.PP
Definition at line 58 of file snmp_agent.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
