.TH "netsnmp_mib_handler_s" 3 "14 Jun 2006" "Version 5.0.11" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netsnmp_mib_handler_s \- the mib handler structure to be registered  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <agent_handler.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBhandler_name\fP"
.br
.ti -1c
.RI "void * \fBmyvoid\fP"
.br
.RI "\fIfor handler's internal use \fP"
.ti -1c
.RI "int(* \fBaccess_method\fP )(struct \fBnetsnmp_mib_handler_s\fP *, struct \fBnetsnmp_handler_registration_s\fP *, struct \fBnetsnmp_agent_request_info_s\fP *, struct \fBnetsnmp_request_info_s\fP *)"
.br
.ti -1c
.RI "\fBnetsnmp_mib_handler_s\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBnetsnmp_mib_handler_s\fP * \fBprev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
the mib handler structure to be registered 
.PP
\fBExamples: \fP
.in +1c
.PP
\fBdelayed_instance.c\fP.
.PP
Definition at line 33 of file agent_handler.h.
.SH "Field Documentation"
.PP 
.SS "void* \fBnetsnmp_mib_handler_s::myvoid\fP"
.PP
for handler's internal use 
.PP
Definition at line 36 of file agent_handler.h.
.PP
Referenced by netsnmp_debug_helper(), netsnmp_find_handler_data_by_name(), netsnmp_get_mode_end_call_handler(), netsnmp_get_multiplexer_handler(), netsnmp_get_table_data_handler(), netsnmp_get_table_data_set_handler(), netsnmp_get_table_handler(), netsnmp_get_table_iterator_handler(), netsnmp_handler_dup(), netsnmp_instance_counter32_handler(), netsnmp_instance_int_handler(), netsnmp_instance_long_handler(), netsnmp_instance_ulong_handler(), netsnmp_mode_end_call_helper(), netsnmp_multiplexer_helper_handler(), netsnmp_old_api_helper(), netsnmp_register_old_api(), netsnmp_register_watched_instance(), netsnmp_register_watched_scalar(), netsnmp_register_watched_timestamp(), netsnmp_table_container_register(), netsnmp_table_data_helper_handler(), netsnmp_table_data_set_helper_handler(), netsnmp_table_iterator_helper_handler(), netsnmp_watched_timestamp_handler(), netsnmp_watcher_helper_handler(), table_helper_handler(), and unregister_mibs_by_session().

.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
