.TH "old_api" 3 "11 Sep 2007" "Version 5.3.2.pre1" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
old_api \- Calls mib \fBmodule\fP code written in the old style of code.  

.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBnetsnmp_mib_handler\fP * \fBget_old_api_handler\fP (void)"
.br
.RI "\fIreturns a old_api handler that should be the final calling handler. \fP"
.ti -1c
.RI "int \fBnetsnmp_register_old_api\fP (const char *moduleName, struct \fBvariable\fP *var, size_t varsize, size_t numvars, oid *mibloc, size_t mibloclen, int priority, int range_subid, oid range_ubound, \fBnetsnmp_session\fP *ss, const char *context, int timeout, int flags)"
.br
.RI "\fIRegisters an old API set into the mib \fBtree\fP. \fP"
.ti -1c
.RI "int \fBnetsnmp_register_mib_table_row\fP (const char *moduleName, struct \fBvariable\fP *var, size_t varsize, size_t numvars, oid *mibloc, size_t mibloclen, int priority, int var_subid, \fBnetsnmp_session\fP *ss, const char *context, int timeout, int flags)"
.br
.RI "\fIregisters a row within a mib table \fP"
.ti -1c
.RI "int \fBnetsnmp_old_api_helper\fP (\fBnetsnmp_mib_handler\fP *handler, \fBnetsnmp_handler_registration\fP *reginfo, \fBnetsnmp_agent_request_info\fP *reqinfo, \fBnetsnmp_request_info\fP *requests)"
.br
.RI "\fIimplements the old_api handler \fP"
.in -1c
.SH "Detailed Description"
.PP 
Calls mib \fBmodule\fP code written in the old style of code. 
.PP
This is a backwards compatilibity \fBmodule\fP that allows code written in the old API to be run under the new handler based architecture. Use it by calling \fBnetsnmp_register_old_api()\fP. 
.SH "Function Documentation"
.PP 
.SS "\fBnetsnmp_mib_handler\fP* get_old_api_handler (void)"
.PP
returns a old_api handler that should be the final calling handler. 
.PP
Don't use this function. Use the \fBnetsnmp_register_old_api()\fP function instead. 
.PP
Definition at line 37 of file old_api.c.
.PP
References netsnmp_create_handler(), and netsnmp_old_api_helper().
.PP
Referenced by netsnmp_register_mib_table_row(), and netsnmp_register_old_api().
.SS "int netsnmp_old_api_helper (\fBnetsnmp_mib_handler\fP * handler, \fBnetsnmp_handler_registration\fP * reginfo, \fBnetsnmp_agent_request_info\fP * reqinfo, \fBnetsnmp_request_info\fP * requests)"
.PP
implements the old_api handler 
.PP
Definition at line 226 of file old_api.c.
.PP
References variable::acl, netsnmp_agent_request_info::asp, netsnmp_old_api_cache::data, variable::findVar, netsnmp_handler_registration::handlerName, variable::magic, netsnmp_agent_request_info::mode, netsnmp_mib_handler::myvoid, variable_list::name, variable::name, variable_list::name_length, variable::namelen, netsnmp_create_data_list(), netsnmp_oid_equals(), netsnmp_request_add_list_data(), netsnmp_request_get_list_data(), netsnmp_set_request_error(), netsnmp_request_info::next, NULL, netsnmp_request_info::requestvb, netsnmp_handler_registration::rootoid, netsnmp_handler_registration::rootoid_len, SNMP_MALLOC_TYPEDEF, snmp_set_var_typed_value(), variable_list::type, variable::type, variable_list::val, variable_list::val_len, and netsnmp_old_api_cache::write_method.
.PP
Referenced by get_old_api_handler().
.SS "int netsnmp_register_mib_table_row (const char * moduleName, struct \fBvariable\fP * var, size_t varsize, size_t numvars, oid * mibloc, size_t mibloclen, int priority, int var_subid, \fBnetsnmp_session\fP * ss, const char * context, int timeout, int flags)"
.PP
registers a row within a mib table 
.PP
Definition at line 107 of file old_api.c.
.SS "int netsnmp_register_old_api (const char * moduleName, struct \fBvariable\fP * var, size_t varsize, size_t numvars, oid * mibloc, size_t mibloclen, int priority, int range_subid, oid range_ubound, \fBnetsnmp_session\fP * ss, const char * context, int timeout, int flags)"
.PP
Registers an old API set into the mib \fBtree\fP. 
.PP
Functionally this mimics the old \fBregister_mib_context()\fP function (and in fact the new \fBregister_mib_context()\fP function merely calls this new old_api one). 
.PP
netsnmp_handler_registration_free(reginfo); already freed 
.PP
Definition at line 48 of file old_api.c.
.PP
Referenced by register_mib_context().
