.TH "netsnmp_agent_request_info_s" 3 "11 Sep 2007" "Version 5.3.2.pre1" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netsnmp_agent_request_info_s \- The agent transaction request structure.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <snmp_agent.h>\fP
.PP
.SH "Detailed Description"
.PP 
The agent transaction request structure. 

.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
