serialize: Calls sub handlers one request at a time.
NAME
serialize: Calls sub handlers one request at a time. - This functionally passes in one request at a time into lower handlers rather than a whole bunch of requests at once.
Functions
netsnmp_mib_handler * netsnmp_get_serialize_handler (void)
returns a serialize handler that can be injected into a given handler chain.
int netsnmp_register_serialize (netsnmp_handler_registration *reginfo)
functionally the same as calling netsnmp_register_handler() but also injects a serialize handler at the same time for you.
int netsnmp_serialize_helper_handler (netsnmp_mib_handler *handler, netsnmp_handler_registration *reginfo, netsnmp_agent_request_info *reqinfo, netsnmp_request_info *requests)
Implements the serial handler.
void netsnmp_init_serialize (void)
initializes the serialize helper which then registers a serialize handler as a run-time injectable handler for configuration file use.
Detailed Description
This functionally passes in one request at a time into lower handlers rather than a whole bunch of requests at once. This is useful for handlers that don't want to iterate through the request lists themselves. Generally, this is probably less efficient so use with caution. The serialize handler might be useable to dynamically fix handlers with broken looping code, however.
Function Documentation
netsnmp_mib_handler* netsnmp_get_serialize_handler (void)
returns a serialize handler that can be injected into a given handler chain. Definition at line 34 of file serialize.c.
References netsnmp_create_handler().
Referenced by netsnmp_init_serialize(), and netsnmp_register_serialize().
void netsnmp_init_serialize (void)
initializes the serialize helper which then registers a serialize handler as a run-time injectable handler for configuration file use. Definition at line 96 of file serialize.c.
References netsnmp_get_serialize_handler(), and netsnmp_register_handler_by_name().
int netsnmp_register_serialize (netsnmp_handler_registration * reginfo)
functionally the same as calling netsnmp_register_handler() but also injects a serialize handler at the same time for you. Definition at line 43 of file serialize.c.
References netsnmp_get_serialize_handler(), netsnmp_handler_registration, netsnmp_inject_handler(), and netsnmp_register_handler().
Referenced by netsnmp_register_instance(), netsnmp_register_read_only_instance(), netsnmp_register_read_only_scalar(), and netsnmp_register_scalar().
int netsnmp_serialize_helper_handler (netsnmp_mib_handler * handler, netsnmp_handler_registration * reginfo, netsnmp_agent_request_info * reqinfo, netsnmp_request_info * requests)
Implements the serial handler. Definition at line 51 of file serialize.c.
References netsnmp_call_next_handler(), netsnmp_handler_registration, netsnmp_mib_handler, and netsnmp_request_info_s::next.