.TH "baby_steps_access_multiplexer: calls individual access methods based on baby_step mode." 3 "23 Sep 2009" "Version 5.5" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
baby_steps_access_multiplexer: calls individual access methods based on baby_step mode. \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBnetsnmp_mib_handler\fP * \fBnetsnmp_baby_steps_access_multiplexer_get\fP (\fBnetsnmp_baby_steps_access_methods\fP *am)"
.br
.RI "\fIreturns a baby_steps handler that can be injected into a given handler chain. \fP"
.ti -1c
.RI "int \fBnetsnmp_baby_step_mode2flag\fP (u_int mode)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBnetsnmp_mib_handler\fP* netsnmp_baby_steps_access_multiplexer_get (\fBnetsnmp_baby_steps_access_methods\fP * am)"
.PP
returns a baby_steps handler that can be injected into a given handler chain. 
.PP
Definition at line 336 of file baby_steps.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
