.TH "netsnmp_handler_registration_s" 3 "24 Nov 2004" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netsnmp_handler_registration_s \- Root registration info.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <agent_handler.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBhandlerName\fP"
.br
.RI "\fIfor mrTable listings, and other uses \fP"
.ti -1c
.RI "char * \fBcontextName\fP"
.br
.RI "\fINULL = default context. \fP"
.ti -1c
.RI "oid * \fBrootoid\fP"
.br
.RI "\fIwhere are we registered at? \fP"
.ti -1c
.RI "size_t \fBrootoid_len\fP"
.br
.ti -1c
.RI "\fBnetsnmp_mib_handler\fP * \fBhandler\fP"
.br
.RI "\fIhandler details \fP"
.ti -1c
.RI "int \fBmodes\fP"
.br
.ti -1c
.RI "int \fBpriority\fP"
.br
.RI "\fImore optional stuff \fP"
.ti -1c
.RI "int \fBrange_subid\fP"
.br
.ti -1c
.RI "oid \fBrange_ubound\fP"
.br
.ti -1c
.RI "int \fBtimeout\fP"
.br
.ti -1c
.RI "int \fBglobal_cacheid\fP"
.br
.ti -1c
.RI "void * \fBmy_reg_void\fP"
.br
.RI "\fIvoid ptr for registeree \fP"
.in -1c
.SH "Detailed Description"
.PP 
Root registration info. 

The variables handlerName, contextName, and rootoid need to be allocated on the heap, when the registration structure is unregistered using \fBunregister_mib_context()\fP the code attempts to free them. 
.PP
\fBExamples: \fP
.in +1c
.PP
\fBdelayed_instance.c\fP.
.PP
Definition at line 94 of file agent_handler.h.
.SH "Field Documentation"
.PP 
.SS "char* \fBnetsnmp_handler_registration_s::contextName\fP"
.PP
NULL = default context. Definition at line 99 of file agent_handler.h.
.PP
Referenced by netsnmp_handler_registration_dup(), netsnmp_handler_registration_free(), netsnmp_register_handler(), netsnmp_register_handler_nocallback(), netsnmp_register_mib_table_row(), netsnmp_register_old_api(), and netsnmp_unregister_handler().
.SS "\fBnetsnmp_mib_handler\fP* \fBnetsnmp_handler_registration_s::handler\fP"
.PP
handler details Definition at line 110 of file agent_handler.h.
.PP
Referenced by netsnmp_find_handler_by_name(), netsnmp_find_table_array_handler(), netsnmp_handler_registration_create(), netsnmp_handler_registration_dup(), netsnmp_handler_registration_free(), netsnmp_inject_handler_before(), netsnmp_register_handler(), netsnmp_register_handler_nocallback(), netsnmp_register_mib_table_row(), netsnmp_register_old_api(), and netsnmp_table_container_register().
.SS "char* \fBnetsnmp_handler_registration_s::handlerName\fP"
.PP
for mrTable listings, and other uses Definition at line 97 of file agent_handler.h.
.PP
Referenced by netsnmp_cache_helper_handler(), netsnmp_handler_registration_create(), netsnmp_handler_registration_dup(), netsnmp_handler_registration_free(), netsnmp_old_api_helper(), netsnmp_register_handler(), netsnmp_register_mib_table_row(), netsnmp_register_old_api(), and netsnmp_table_iterator_helper_handler().
.SS "void* \fBnetsnmp_handler_registration_s::my_reg_void\fP"
.PP
void ptr for registeree Definition at line 125 of file agent_handler.h.
.SS "int \fBnetsnmp_handler_registration_s::priority\fP"
.PP
more optional stuff Definition at line 116 of file agent_handler.h.
.PP
Referenced by netsnmp_handler_registration_create(), netsnmp_handler_registration_dup(), netsnmp_register_handler(), netsnmp_register_handler_nocallback(), netsnmp_register_mib_table_row(), netsnmp_register_old_api(), and netsnmp_unregister_handler().
.SS "oid* \fBnetsnmp_handler_registration_s::rootoid\fP"
.PP
where are we registered at? Definition at line 104 of file agent_handler.h.
.PP
Referenced by netsnmp_cache_helper_handler(), netsnmp_handler_registration_create(), netsnmp_handler_registration_dup(), netsnmp_handler_registration_free(), netsnmp_old_api_helper(), netsnmp_register_cache_handler(), netsnmp_register_handler(), netsnmp_register_handler_nocallback(), netsnmp_register_mib_table_row(), netsnmp_register_old_api(), netsnmp_register_read_only_scalar(), netsnmp_register_scalar(), netsnmp_row_merge_helper_handler(), netsnmp_table_build_oid(), netsnmp_table_build_oid_from_index(), netsnmp_table_data_build_result(), netsnmp_table_data_helper_handler(), netsnmp_table_iterator_helper_handler(), netsnmp_unregister_handler(), and table_helper_handler().

.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
