.TH "variable_list" 3 "23 Sep 2009" "Version 5.5" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
variable_list \- 
.PP
The netsnmp \fBvariable\fP list binding structure, it's typedef'd to netsnmp_variable_list.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBvariable_list\fP * \fBnext_variable\fP"
.br
.RI "\fINULL for last \fBvariable\fP. \fP"
.ti -1c
.RI "oid * \fBname\fP"
.br
.RI "\fIObject identifier of \fBvariable\fP. \fP"
.ti -1c
.RI "size_t \fBname_length\fP"
.br
.RI "\fInumber of subid's in name \fP"
.ti -1c
.RI "u_char \fBtype\fP"
.br
.RI "\fIASN type of \fBvariable\fP. \fP"
.ti -1c
.RI "\fBnetsnmp_vardata\fP \fBval\fP"
.br
.RI "\fIvalue of \fBvariable\fP \fP"
.ti -1c
.RI "size_t \fBval_len\fP"
.br
.RI "\fIthe length of the value to be copied into buf \fP"
.ti -1c
.RI "oid \fBname_loc\fP [MAX_OID_LEN]"
.br
.RI "\fI90 percentile < 24. \fP"
.ti -1c
.RI "u_char \fBbuf\fP [40]"
.br
.RI "\fI90 percentile < 40. \fP"
.ti -1c
.RI "void * \fBdata\fP"
.br
.RI "\fI(Opaque) hook for additional data \fP"
.ti -1c
.RI "void(* \fBdataFreeHook\fP )(void *)"
.br
.RI "\fIcallback to free above \fP"
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The netsnmp \fBvariable\fP list binding structure, it's typedef'd to netsnmp_variable_list. 
.PP
\fBExamples: \fP
.in +1c
.PP
\fBnotification.c\fP.
.PP
Definition at line 112 of file types.h.
.SH "Field Documentation"
.PP 
.SS "u_char \fBvariable_list::buf\fP[40]"
.PP
90 percentile < 40. 
.PP
Definition at line 128 of file types.h.
.SS "void* \fBvariable_list::data\fP"
.PP
(Opaque) hook for additional data 
.PP
Definition at line 130 of file types.h.
.SS "void(* \fBvariable_list::dataFreeHook\fP)(void *)"
.PP
callback to free above 
.SS "oid* \fBvariable_list::name\fP"
.PP
Object identifier of \fBvariable\fP. 
.PP
Definition at line 116 of file types.h.
.SS "size_t \fBvariable_list::name_length\fP"
.PP
number of subid's in name 
.PP
Definition at line 118 of file types.h.
.SS "oid \fBvariable_list::name_loc\fP[MAX_OID_LEN]"
.PP
90 percentile < 24. 
.PP
Definition at line 126 of file types.h.
.SS "struct \fBvariable_list\fP* \fBvariable_list::next_variable\fP\fC [read]\fP"
.PP
NULL for last \fBvariable\fP. 
.PP
Definition at line 114 of file types.h.
.SS "u_char \fBvariable_list::type\fP"
.PP
ASN type of \fBvariable\fP. 
.PP
\fBExamples: \fP
.in +1c
\fBdelayed_instance.c\fP.
.PP
Definition at line 120 of file types.h.
.SS "\fBnetsnmp_vardata\fP \fBvariable_list::val\fP"
.PP
value of \fBvariable\fP 
.PP
\fBExamples: \fP
.in +1c
\fBdelayed_instance.c\fP.
.PP
Definition at line 122 of file types.h.
.SS "size_t \fBvariable_list::val_len\fP"
.PP
the length of the value to be copied into buf 
.PP
Definition at line 124 of file types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
