.TH "The Net-SNMP agent" 3 "30 Jun 2005" "Version 5.2.1.rc3" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
The Net-SNMP agent \- The snmp agent responds to SNMP queries from management stations.  

.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBNet-SNMP Agent handler and extensibility API\fP"
.br
.ti -1c
.RI "\fBMaintain a registry of MIB subtrees, together with related information regarding mibmodule, sessions, etc\fP"
.br
.ti -1c
.RI "\fBTrap generation routines for mib modules to use\fP"
.br
.ti -1c
.RI "\fBnet-snmp agent related processing\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The snmp agent responds to SNMP queries from management stations. 
.PP

