#ifndef AGENT_CALLBACKS_H
#define AGENT_CALLBACKS_H

#define SNMPD_CALLBACK_ACM_CHECK         0
#define SNMPD_CALLBACK_REGISTER_OID      1
#define SNMPD_CALLBACK_UNREGISTER_OID    2
#define SNMPD_CALLBACK_REG_SYSOR         3
#define SNMPD_CALLBACK_UNREG_SYSOR       4
#define SNMPD_CALLBACK_ACM_CHECK_INITIAL 5

#endif /* AGENT_CALLBACKS_H */
