# DO NOT DELETE THIS LINE -- make depend depends on it.

./agent_handler.lo: ../include/net-snmp/net-snmp-config.h
./agent_handler.lo: ../include/net-snmp/system/linux.h
./agent_handler.lo: ../include/net-snmp/system/sysv.h
./agent_handler.lo: ../include/net-snmp/system/generic.h
./agent_handler.lo: ../include/net-snmp/machine/generic.h
./agent_handler.lo: ./mibgroup/mibincl.h 
./agent_handler.lo: ../include/net-snmp/asn1.h ../include/net-snmp/snmp_api.h
./agent_handler.lo: ../include/net-snmp/snmp_impl.h
./agent_handler.lo: ../include/net-snmp/snmp_client.h
./agent_handler.lo: ../include/net-snmp/agent/snmp_vars.h
./agent_handler.lo: ../include/net-snmp/agent/agent_registry.h
./agent_handler.lo: ../include/net-snmp/agent/snmp_agent.h
./agent_handler.lo: ../include/net-snmp/tools.h
./agent_handler.lo: ../include/net-snmp/data_list.h
./agent_handler.lo: ../include/net-snmp/snmp_impl.h
./agent_handler.lo: ../include/net-snmp/tools.h
./agent_handler.lo: ../include/net-snmp/agent/agent_read_config.h
./agent_handler.lo: ../include/net-snmp/agent/agent_handler.h
./agent_handler.lo: ../include/net-snmp/agent/agent_registry.h
./agent_handler.lo: ../include/net-snmp/agent/var_struct.h
./agent_handler.lo: ../include/net-snmp/snmp.h ../include/net-snmp/mib.h
./agent_handler.lo: ../include/net-snmp/snmp_debug.h
./agent_handler.lo: ../include/net-snmp/snmp_logging.h 
./agent_handler.lo: ../include/net-snmp/snmp_alarm.h
./agent_handler.lo: ../include/net-snmp/read_config.h
./agent_handler.lo: ../include/net-snmp/agent/agent_trap.h
./agent_handler.lo: ../include/net-snmp/callback.h
./agent_handler.lo: ../include/net-snmp/agent/snmp_agent.h
./agent_handler.lo: ../include/net-snmp/snmp_enum.h
./agent_handler.lo: ../include/net-snmp/agent/bulk_to_next.h
./agent_index.lo: ../include/net-snmp/net-snmp-config.h
./agent_index.lo: ../include/net-snmp/system/linux.h
./agent_index.lo: ../include/net-snmp/system/sysv.h
./agent_index.lo: ../include/net-snmp/system/generic.h
./agent_index.lo: ../include/net-snmp/machine/generic.h 
./agent_index.lo:  ./mibgroup/mibincl.h
./agent_index.lo:  ../include/net-snmp/asn1.h
./agent_index.lo: ../include/net-snmp/snmp_api.h
./agent_index.lo: ../include/net-snmp/snmp_impl.h
./agent_index.lo: ../include/net-snmp/snmp_client.h
./agent_index.lo: ../include/net-snmp/agent/snmp_vars.h
./agent_index.lo: ../include/net-snmp/agent/agent_registry.h
./agent_index.lo: ../include/net-snmp/agent/snmp_agent.h
./agent_index.lo: ../include/net-snmp/tools.h ../include/net-snmp/data_list.h
./agent_index.lo: ../include/net-snmp/snmp_impl.h ../include/net-snmp/tools.h
./agent_index.lo: ../include/net-snmp/agent/agent_read_config.h
./agent_index.lo: ../include/net-snmp/agent/agent_handler.h
./agent_index.lo: ../include/net-snmp/agent/agent_registry.h
./agent_index.lo: ../include/net-snmp/agent/var_struct.h
./agent_index.lo: ../include/net-snmp/snmp.h ../include/net-snmp/mib.h
./agent_index.lo: ../include/net-snmp/snmp_debug.h
./agent_index.lo: ../include/net-snmp/snmp_logging.h 
./agent_index.lo:  ../include/net-snmp/snmp_alarm.h
./agent_index.lo: ../include/net-snmp/read_config.h
./agent_index.lo: ../include/net-snmp/agent/agent_trap.h
./agent_index.lo: ../include/net-snmp/callback.h
./agent_index.lo: ../include/net-snmp/default_store.h
./agent_index.lo: ../include/net-snmp/agent/ds_agent.h
./agent_index.lo: ../include/net-snmp/agent/agent_callbacks.h
./agent_index.lo: ../include/net-snmp/agent/agent_index.h
./agent_index.lo: ../include/net-snmp/snmp_secmod.h snmpd.h mibgroup/struct.h
./agent_index.lo: ../include/net-snmp/agent/table.h
./agent_index.lo: ../include/net-snmp/agent/table_iterator.h
./agent_index.lo: ./mibgroup/mib_module_includes.h mibgroup/mibII.h
./agent_index.lo: mibgroup/ucd_snmp.h mibgroup/snmpv3mibs.h
./agent_index.lo: mibgroup/notification.h mibgroup/agentx.h
./agent_index.lo: mibgroup/agent_mibs.h mibgroup/testhandler.h
./agent_index.lo: mibgroup/testdelayed.h mibgroup/examples/example.h
./agent_index.lo: mibgroup/agent/nsTransactionTable.h mibgroup/policy.h
./agent_index.lo: mibgroup/host.h mibgroup/mibII/system_mib.h
./agent_index.lo: mibgroup/mibII/sysORTable.h mibgroup/mibII/at.h
./agent_index.lo: mibgroup/mibII/interfaces.h mibgroup/mibII/snmp_mib.h
./agent_index.lo: mibgroup/mibII/tcp.h mibgroup/mibII/icmp.h
./agent_index.lo: mibgroup/mibII/ip.h mibgroup/mibII/var_route.h
./agent_index.lo: mibgroup/mibII/route_write.h mibgroup/mibII/udp.h
./agent_index.lo: mibgroup/mibII/vacm_vars.h ../include/net-snmp/vacm.h
./agent_index.lo: mibgroup/ucd-snmp/memory.h ./mibgroup/mibdefs.h
./agent_index.lo: mibgroup/ucd-snmp/vmstat.h mibgroup/ucd-snmp/proc.h
./agent_index.lo: mibgroup/ucd-snmp/versioninfo.h mibgroup/ucd-snmp/pass.h
./agent_index.lo: mibgroup/ucd-snmp/pass_persist.h mibgroup/ucd-snmp/disk.h
./agent_index.lo: mibgroup/ucd-snmp/loadave.h mibgroup/ucd-snmp/extensible.h
./agent_index.lo: mibgroup/ucd-snmp/errormib.h mibgroup/ucd-snmp/registry.h
./agent_index.lo: mibgroup/ucd-snmp/file.h mibgroup/ucd-snmp/dlmod.h
./agent_index.lo: mibgroup/ucd-snmp/proxy.h mibgroup/snmpv3/snmpEngine.h
./agent_index.lo: mibgroup/snmpv3/snmpMPDStats.h mibgroup/snmpv3/usmStats.h
./agent_index.lo: mibgroup/snmpv3/usmUser.h ../include/net-snmp/snmpusm.h
./agent_index.lo: mibgroup/notification/snmpNotifyTable.h
./agent_index.lo: mibgroup/notification/snmpNotifyFilterTable.h
./agent_index.lo: mibgroup/notification/snmpNotifyFilterProfileTable.h
./agent_index.lo: mibgroup/agentx/master.h mibgroup/agentx/subagent.h
./agent_index.lo: mibgroup/util_funcs.h mibgroup/struct.h
./agent_index.lo: mibgroup/policy/policyEndpointToGroupTable.h
./agent_index.lo: mibgroup/policy/policyGroupContentsTable.h
./agent_index.lo: mibgroup/policy/policyRuleDefinitionTable.h
./agent_index.lo: mibgroup/policy/conditionsInRuleTable.h
./agent_index.lo: mibgroup/policy/conditionTable.h
./agent_index.lo: mibgroup/policy/filtersInConditionTable.h
./agent_index.lo: mibgroup/policy/filterTable.h
./agent_index.lo: mibgroup/policy/saStaticActionTable.h
./agent_index.lo: mibgroup/host/hr_system.h mibgroup/host/hr_storage.h
./agent_index.lo: mibgroup/host/hr_device.h mibgroup/host/hr_other.h
./agent_index.lo: mibgroup/host/hr_proc.h mibgroup/host/hr_network.h
./agent_index.lo: mibgroup/host/hr_print.h mibgroup/host/hr_disk.h
./agent_index.lo: mibgroup/host/hr_partition.h mibgroup/host/hr_filesys.h
./agent_index.lo: mibgroup/host/hr_swrun.h mibgroup/host/hr_swinst.h
./agent_index.lo: mibgroup/mibII/kernel_linux.h mibgroup/mibII/tcpTable.h
./agent_index.lo: mibgroup/mibII/ipAddr.h mibgroup/mibII/var_route.h
./agent_index.lo: mibgroup/mibII/route_write.h mibgroup/mibII/udpTable.h
./agent_index.lo: mibgroup/mibII/vacm_context.h mibgroup/header_complex.h
./agent_index.lo: mibgroup/target.h mibgroup/agentx/protocol.h
./agent_index.lo: mibgroup/agentx/client.h mibgroup/agentx/master_admin.h
./agent_index.lo: mibgroup/agentx/agentx_config.h
./agent_index.lo: mibgroup/policy/policy_iterator.h
./agent_index.lo: mibgroup/target/snmpTargetAddrEntry.h
./agent_index.lo: mibgroup/target/snmpTargetParamsEntry.h
./agent_index.lo: mibgroup/target/target.h mibgroup/target/target_counters.h
./agent_read_config.lo: ../include/net-snmp/net-snmp-config.h
./agent_read_config.lo: ../include/net-snmp/system/linux.h
./agent_read_config.lo: ../include/net-snmp/system/sysv.h
./agent_read_config.lo: ../include/net-snmp/system/generic.h
./agent_read_config.lo: ../include/net-snmp/machine/generic.h
./agent_read_config.lo:  ./mibgroup/mibincl.h
./agent_read_config.lo:  ../include/net-snmp/asn1.h
./agent_read_config.lo: ../include/net-snmp/snmp_api.h
./agent_read_config.lo: ../include/net-snmp/snmp_impl.h
./agent_read_config.lo: ../include/net-snmp/snmp_client.h
./agent_read_config.lo: ../include/net-snmp/agent/snmp_vars.h
./agent_read_config.lo: ../include/net-snmp/agent/agent_registry.h
./agent_read_config.lo: ../include/net-snmp/agent/snmp_agent.h
./agent_read_config.lo: ../include/net-snmp/tools.h
./agent_read_config.lo: ../include/net-snmp/data_list.h
./agent_read_config.lo: ../include/net-snmp/snmp_impl.h
./agent_read_config.lo: ../include/net-snmp/tools.h
./agent_read_config.lo: ../include/net-snmp/agent/agent_read_config.h
./agent_read_config.lo: ../include/net-snmp/agent/agent_handler.h
./agent_read_config.lo: ../include/net-snmp/agent/agent_registry.h
./agent_read_config.lo: ../include/net-snmp/agent/var_struct.h
./agent_read_config.lo: ../include/net-snmp/snmp.h ../include/net-snmp/mib.h
./agent_read_config.lo: ../include/net-snmp/snmp_debug.h
./agent_read_config.lo: ../include/net-snmp/snmp_logging.h
./agent_read_config.lo: ../include/net-snmp/snmp_alarm.h
./agent_read_config.lo: ../include/net-snmp/read_config.h
./agent_read_config.lo: ../include/net-snmp/agent/agent_trap.h
./agent_read_config.lo: ../include/net-snmp/callback.h
./agent_read_config.lo: ../include/net-snmp/snmp_secmod.h
./agent_read_config.lo: ../include/net-snmp/snmpusm.h mibgroup/struct.h
./agent_read_config.lo: ../include/net-snmp/agent/snmp_agent.h snmpd.h
./agent_read_config.lo: ../include/net-snmp/system.h
./agent_read_config.lo: ../include/net-snmp/agent/agent_callbacks.h
./agent_read_config.lo: ../include/net-snmp/default_store.h
./agent_read_config.lo: ../include/net-snmp/agent/ds_agent.h
./agent_read_config.lo: ../include/net-snmp/agent/table.h
./agent_read_config.lo: ../include/net-snmp/agent/table_iterator.h
./agent_read_config.lo: ../include/net-snmp/agent/table_data.h
./agent_read_config.lo: ../include/net-snmp/agent/table_dataset.h
./agent_read_config.lo: ./mibgroup/mib_module_includes.h mibgroup/mibII.h
./agent_read_config.lo: mibgroup/ucd_snmp.h mibgroup/snmpv3mibs.h
./agent_read_config.lo: mibgroup/notification.h mibgroup/agentx.h
./agent_read_config.lo: mibgroup/agent_mibs.h mibgroup/testhandler.h
./agent_read_config.lo: mibgroup/testdelayed.h mibgroup/examples/example.h
./agent_read_config.lo: mibgroup/agent/nsTransactionTable.h mibgroup/policy.h
./agent_read_config.lo: mibgroup/host.h mibgroup/mibII/system_mib.h
./agent_read_config.lo: mibgroup/mibII/sysORTable.h mibgroup/mibII/at.h
./agent_read_config.lo: mibgroup/mibII/interfaces.h mibgroup/mibII/snmp_mib.h
./agent_read_config.lo: mibgroup/mibII/tcp.h mibgroup/mibII/icmp.h
./agent_read_config.lo: mibgroup/mibII/ip.h mibgroup/mibII/var_route.h
./agent_read_config.lo: mibgroup/mibII/route_write.h mibgroup/mibII/udp.h
./agent_read_config.lo: mibgroup/mibII/vacm_vars.h ../include/net-snmp/vacm.h
./agent_read_config.lo: mibgroup/ucd-snmp/memory.h ./mibgroup/mibdefs.h
./agent_read_config.lo: mibgroup/ucd-snmp/vmstat.h mibgroup/ucd-snmp/proc.h
./agent_read_config.lo: mibgroup/ucd-snmp/versioninfo.h
./agent_read_config.lo: mibgroup/ucd-snmp/pass.h
./agent_read_config.lo: mibgroup/ucd-snmp/pass_persist.h
./agent_read_config.lo: mibgroup/ucd-snmp/disk.h mibgroup/ucd-snmp/loadave.h
./agent_read_config.lo: mibgroup/ucd-snmp/extensible.h
./agent_read_config.lo: mibgroup/ucd-snmp/errormib.h
./agent_read_config.lo: mibgroup/ucd-snmp/registry.h mibgroup/ucd-snmp/file.h
./agent_read_config.lo: mibgroup/ucd-snmp/dlmod.h mibgroup/ucd-snmp/proxy.h
./agent_read_config.lo: mibgroup/snmpv3/snmpEngine.h
./agent_read_config.lo: mibgroup/snmpv3/snmpMPDStats.h
./agent_read_config.lo: mibgroup/snmpv3/usmStats.h mibgroup/snmpv3/usmUser.h
./agent_read_config.lo: mibgroup/notification/snmpNotifyTable.h
./agent_read_config.lo: mibgroup/notification/snmpNotifyFilterTable.h
./agent_read_config.lo: mibgroup/notification/snmpNotifyFilterProfileTable.h
./agent_read_config.lo: mibgroup/agentx/master.h mibgroup/agentx/subagent.h
./agent_read_config.lo: mibgroup/util_funcs.h mibgroup/struct.h
./agent_read_config.lo: mibgroup/policy/policyEndpointToGroupTable.h
./agent_read_config.lo: mibgroup/policy/policyGroupContentsTable.h
./agent_read_config.lo: mibgroup/policy/policyRuleDefinitionTable.h
./agent_read_config.lo: mibgroup/policy/conditionsInRuleTable.h
./agent_read_config.lo: mibgroup/policy/conditionTable.h
./agent_read_config.lo: mibgroup/policy/filtersInConditionTable.h
./agent_read_config.lo: mibgroup/policy/filterTable.h
./agent_read_config.lo: mibgroup/policy/saStaticActionTable.h
./agent_read_config.lo: mibgroup/host/hr_system.h mibgroup/host/hr_storage.h
./agent_read_config.lo: mibgroup/host/hr_device.h mibgroup/host/hr_other.h
./agent_read_config.lo: mibgroup/host/hr_proc.h mibgroup/host/hr_network.h
./agent_read_config.lo: mibgroup/host/hr_print.h mibgroup/host/hr_disk.h
./agent_read_config.lo: mibgroup/host/hr_partition.h
./agent_read_config.lo: mibgroup/host/hr_filesys.h mibgroup/host/hr_swrun.h
./agent_read_config.lo: mibgroup/host/hr_swinst.h
./agent_read_config.lo: mibgroup/mibII/kernel_linux.h
./agent_read_config.lo: mibgroup/mibII/tcpTable.h mibgroup/mibII/ipAddr.h
./agent_read_config.lo: mibgroup/mibII/var_route.h
./agent_read_config.lo: mibgroup/mibII/route_write.h
./agent_read_config.lo: mibgroup/mibII/udpTable.h
./agent_read_config.lo: mibgroup/mibII/vacm_context.h
./agent_read_config.lo: mibgroup/header_complex.h mibgroup/target.h
./agent_read_config.lo: mibgroup/agentx/protocol.h mibgroup/agentx/client.h
./agent_read_config.lo: mibgroup/agentx/master_admin.h
./agent_read_config.lo: mibgroup/agentx/agentx_config.h
./agent_read_config.lo: mibgroup/policy/policy_iterator.h
./agent_read_config.lo: mibgroup/target/snmpTargetAddrEntry.h
./agent_read_config.lo: mibgroup/target/snmpTargetParamsEntry.h
./agent_read_config.lo: mibgroup/target/target.h
./agent_read_config.lo: mibgroup/target/target_counters.h
./agent_read_config.lo: ./mibgroup/mib_module_dot_conf.h
./agent_registry.lo: ../include/net-snmp/net-snmp-config.h
./agent_registry.lo: ../include/net-snmp/system/linux.h
./agent_registry.lo: ../include/net-snmp/system/sysv.h
./agent_registry.lo: ../include/net-snmp/system/generic.h
./agent_registry.lo: ../include/net-snmp/machine/generic.h
./agent_registry.lo:  ./mibgroup/mibincl.h
./agent_registry.lo:  ../include/net-snmp/asn1.h
./agent_registry.lo: ../include/net-snmp/snmp_api.h
./agent_registry.lo: ../include/net-snmp/snmp_impl.h
./agent_registry.lo: ../include/net-snmp/snmp_client.h
./agent_registry.lo: ../include/net-snmp/agent/snmp_vars.h
./agent_registry.lo: ../include/net-snmp/agent/agent_registry.h
./agent_registry.lo: ../include/net-snmp/agent/snmp_agent.h
./agent_registry.lo: ../include/net-snmp/tools.h
./agent_registry.lo: ../include/net-snmp/data_list.h
./agent_registry.lo: ../include/net-snmp/snmp_impl.h
./agent_registry.lo: ../include/net-snmp/tools.h
./agent_registry.lo: ../include/net-snmp/agent/agent_read_config.h
./agent_registry.lo: ../include/net-snmp/agent/agent_handler.h
./agent_registry.lo: ../include/net-snmp/agent/agent_registry.h
./agent_registry.lo: ../include/net-snmp/agent/var_struct.h
./agent_registry.lo: ../include/net-snmp/snmp.h ../include/net-snmp/mib.h
./agent_registry.lo: ../include/net-snmp/snmp_debug.h
./agent_registry.lo: ../include/net-snmp/snmp_logging.h 
./agent_registry.lo: ../include/net-snmp/snmp_alarm.h
./agent_registry.lo: ../include/net-snmp/read_config.h
./agent_registry.lo: ../include/net-snmp/agent/agent_trap.h
./agent_registry.lo: ../include/net-snmp/callback.h
./agent_registry.lo: ../include/net-snmp/default_store.h
./agent_registry.lo: ../include/net-snmp/agent/ds_agent.h
./agent_registry.lo: ../include/net-snmp/agent/agent_callbacks.h
./agent_registry.lo: ../include/net-snmp/snmp_secmod.h
./agent_registry.lo: ../include/net-snmp/vacm.h snmpd.h mibgroup/struct.h
./agent_registry.lo: ../include/net-snmp/agent/old_api.h
./agent_registry.lo: ../include/net-snmp/agent/null.h
./agent_registry.lo: ../include/net-snmp/agent/table.h
./agent_registry.lo: ../include/net-snmp/agent/table_iterator.h
./agent_registry.lo: ./mibgroup/mib_module_includes.h mibgroup/mibII.h
./agent_registry.lo: mibgroup/ucd_snmp.h mibgroup/snmpv3mibs.h
./agent_registry.lo: mibgroup/notification.h mibgroup/agentx.h
./agent_registry.lo: mibgroup/agent_mibs.h mibgroup/testhandler.h
./agent_registry.lo: mibgroup/testdelayed.h mibgroup/examples/example.h
./agent_registry.lo: mibgroup/agent/nsTransactionTable.h mibgroup/policy.h
./agent_registry.lo: mibgroup/host.h mibgroup/mibII/system_mib.h
./agent_registry.lo: mibgroup/mibII/sysORTable.h mibgroup/mibII/at.h
./agent_registry.lo: mibgroup/mibII/interfaces.h mibgroup/mibII/snmp_mib.h
./agent_registry.lo: mibgroup/mibII/tcp.h mibgroup/mibII/icmp.h
./agent_registry.lo: mibgroup/mibII/ip.h mibgroup/mibII/var_route.h
./agent_registry.lo: mibgroup/mibII/route_write.h mibgroup/mibII/udp.h
./agent_registry.lo: mibgroup/mibII/vacm_vars.h mibgroup/ucd-snmp/memory.h
./agent_registry.lo: ./mibgroup/mibdefs.h mibgroup/ucd-snmp/vmstat.h
./agent_registry.lo: mibgroup/ucd-snmp/proc.h mibgroup/ucd-snmp/versioninfo.h
./agent_registry.lo: mibgroup/ucd-snmp/pass.h
./agent_registry.lo: mibgroup/ucd-snmp/pass_persist.h
./agent_registry.lo: mibgroup/ucd-snmp/disk.h mibgroup/ucd-snmp/loadave.h
./agent_registry.lo: mibgroup/ucd-snmp/extensible.h
./agent_registry.lo: mibgroup/ucd-snmp/errormib.h
./agent_registry.lo: mibgroup/ucd-snmp/registry.h mibgroup/ucd-snmp/file.h
./agent_registry.lo: mibgroup/ucd-snmp/dlmod.h mibgroup/ucd-snmp/proxy.h
./agent_registry.lo: mibgroup/snmpv3/snmpEngine.h
./agent_registry.lo: mibgroup/snmpv3/snmpMPDStats.h
./agent_registry.lo: mibgroup/snmpv3/usmStats.h mibgroup/snmpv3/usmUser.h
./agent_registry.lo: ../include/net-snmp/snmpusm.h
./agent_registry.lo: mibgroup/notification/snmpNotifyTable.h
./agent_registry.lo: mibgroup/notification/snmpNotifyFilterTable.h
./agent_registry.lo: mibgroup/notification/snmpNotifyFilterProfileTable.h
./agent_registry.lo: mibgroup/agentx/master.h mibgroup/agentx/subagent.h
./agent_registry.lo: mibgroup/util_funcs.h mibgroup/struct.h
./agent_registry.lo: mibgroup/policy/policyEndpointToGroupTable.h
./agent_registry.lo: mibgroup/policy/policyGroupContentsTable.h
./agent_registry.lo: mibgroup/policy/policyRuleDefinitionTable.h
./agent_registry.lo: mibgroup/policy/conditionsInRuleTable.h
./agent_registry.lo: mibgroup/policy/conditionTable.h
./agent_registry.lo: mibgroup/policy/filtersInConditionTable.h
./agent_registry.lo: mibgroup/policy/filterTable.h
./agent_registry.lo: mibgroup/policy/saStaticActionTable.h
./agent_registry.lo: mibgroup/host/hr_system.h mibgroup/host/hr_storage.h
./agent_registry.lo: mibgroup/host/hr_device.h mibgroup/host/hr_other.h
./agent_registry.lo: mibgroup/host/hr_proc.h mibgroup/host/hr_network.h
./agent_registry.lo: mibgroup/host/hr_print.h mibgroup/host/hr_disk.h
./agent_registry.lo: mibgroup/host/hr_partition.h mibgroup/host/hr_filesys.h
./agent_registry.lo: mibgroup/host/hr_swrun.h mibgroup/host/hr_swinst.h
./agent_registry.lo: mibgroup/mibII/kernel_linux.h mibgroup/mibII/tcpTable.h
./agent_registry.lo: mibgroup/mibII/ipAddr.h mibgroup/mibII/var_route.h
./agent_registry.lo: mibgroup/mibII/route_write.h mibgroup/mibII/udpTable.h
./agent_registry.lo: mibgroup/mibII/vacm_context.h mibgroup/header_complex.h
./agent_registry.lo: mibgroup/target.h mibgroup/agentx/protocol.h
./agent_registry.lo: mibgroup/agentx/client.h mibgroup/agentx/master_admin.h
./agent_registry.lo: mibgroup/agentx/agentx_config.h
./agent_registry.lo: mibgroup/policy/policy_iterator.h
./agent_registry.lo: mibgroup/target/snmpTargetAddrEntry.h
./agent_registry.lo: mibgroup/target/snmpTargetParamsEntry.h
./agent_registry.lo: mibgroup/target/target.h
./agent_registry.lo: mibgroup/target/target_counters.h
./agent_trap.lo: ../include/net-snmp/net-snmp-config.h
./agent_trap.lo: ../include/net-snmp/system/linux.h
./agent_trap.lo: ../include/net-snmp/system/sysv.h
./agent_trap.lo: ../include/net-snmp/system/generic.h
./agent_trap.lo: ../include/net-snmp/machine/generic.h 
./agent_trap.lo: ../include/net-snmp/getopt.h ../include/net-snmp/asn1.h
./agent_trap.lo: ../include/net-snmp/snmp_api.h
./agent_trap.lo: ../include/net-snmp/snmp_impl.h 
./agent_trap.lo: ../include/net-snmp/snmp_client.h ../include/net-snmp/snmp.h
./agent_trap.lo: ../include/net-snmp/system.h
./agent_trap.lo: ../include/net-snmp/read_config.h
./agent_trap.lo: ../include/net-snmp/snmp_debug.h
./agent_trap.lo: ../include/net-snmp/snmp_parse_args.h
./agent_trap.lo: ../include/net-snmp/agent/agent_trap.h
./agent_trap.lo: ../include/net-snmp/callback.h
./agent_trap.lo: ../include/net-snmp/agent/agent_callbacks.h
./agent_trap.lo: ../include/net-snmp/tools.h
./agent_trap.lo: ../include/net-snmp/snmp_logging.h 
./agent_trap.lo: ../include/net-snmp/snmp_transport.h
./agent_trap.lo: ../include/net-snmp/asn1.h
./auto_nlist.lo: ../include/net-snmp/net-snmp-config.h
./auto_nlist.lo: ../include/net-snmp/system/linux.h
./auto_nlist.lo: ../include/net-snmp/system/sysv.h
./auto_nlist.lo: ../include/net-snmp/system/generic.h
./auto_nlist.lo: ../include/net-snmp/machine/generic.h
./kernel.lo: ../include/net-snmp/net-snmp-config.h
./kernel.lo: ../include/net-snmp/system/linux.h
./kernel.lo: ../include/net-snmp/system/sysv.h
./kernel.lo: ../include/net-snmp/system/generic.h
./kernel.lo: ../include/net-snmp/machine/generic.h
./mib_modules.lo: ../include/net-snmp/net-snmp-config.h
./mib_modules.lo: ../include/net-snmp/system/linux.h
./mib_modules.lo: ../include/net-snmp/system/sysv.h
./mib_modules.lo: ../include/net-snmp/system/generic.h
./mib_modules.lo: ../include/net-snmp/machine/generic.h 
./mib_modules.lo:  ../include/net-snmp/asn1.h
./mib_modules.lo: ../include/net-snmp/snmp_api.h
./mib_modules.lo: ../include/net-snmp/snmp_impl.h 
./mib_modules.lo:  ../include/net-snmp/system.h
./mib_modules.lo: ../include/net-snmp/read_config.h
./mib_modules.lo: ../include/net-snmp/snmp.h ../include/net-snmp/mib.h m2m.h
./mib_modules.lo: ../include/net-snmp/agent/snmp_agent.h
./mib_modules.lo: ../include/net-snmp/agent/agent_handler.h
./mib_modules.lo: ../include/net-snmp/agent/snmp_vars.h
./mib_modules.lo: ../include/net-snmp/agent/agent_registry.h
./mib_modules.lo: ../include/net-snmp/agent/snmp_agent.h
./mib_modules.lo: ../include/net-snmp/tools.h ../include/net-snmp/data_list.h
./mib_modules.lo: ../include/net-snmp/snmp_impl.h ../include/net-snmp/tools.h
./mib_modules.lo: ../include/net-snmp/agent/agent_read_config.h
./mib_modules.lo: ../include/net-snmp/snmpv3.h ../include/net-snmp/callback.h
./mib_modules.lo: ../include/net-snmp/snmp_alarm.h
./mib_modules.lo: ../include/net-snmp/default_store.h
./mib_modules.lo: ../include/net-snmp/snmp_debug.h
./mib_modules.lo: ../include/net-snmp/agent/ds_agent.h
./mib_modules.lo: ../include/net-snmp/snmp_secmod.h mibgroup/struct.h
./mib_modules.lo: ../include/net-snmp/agent/mib_modules.h
./mib_modules.lo: ../include/net-snmp/agent/table.h
./mib_modules.lo: ../include/net-snmp/agent/table_iterator.h
./mib_modules.lo: ./mibgroup/mib_module_includes.h mibgroup/mibII.h
./mib_modules.lo: mibgroup/ucd_snmp.h mibgroup/snmpv3mibs.h
./mib_modules.lo: mibgroup/notification.h mibgroup/agentx.h
./mib_modules.lo: mibgroup/agent_mibs.h mibgroup/testhandler.h
./mib_modules.lo: mibgroup/testdelayed.h mibgroup/examples/example.h
./mib_modules.lo: mibgroup/agent/nsTransactionTable.h mibgroup/policy.h
./mib_modules.lo: mibgroup/host.h mibgroup/mibII/system_mib.h
./mib_modules.lo: mibgroup/mibII/sysORTable.h mibgroup/mibII/at.h
./mib_modules.lo: mibgroup/mibII/interfaces.h mibgroup/mibII/snmp_mib.h
./mib_modules.lo: mibgroup/mibII/tcp.h mibgroup/mibII/icmp.h
./mib_modules.lo: mibgroup/mibII/ip.h mibgroup/mibII/var_route.h
./mib_modules.lo: mibgroup/mibII/route_write.h mibgroup/mibII/udp.h
./mib_modules.lo: mibgroup/mibII/vacm_vars.h ../include/net-snmp/vacm.h
./mib_modules.lo: mibgroup/ucd-snmp/memory.h ./mibgroup/mibdefs.h
./mib_modules.lo: mibgroup/ucd-snmp/vmstat.h mibgroup/ucd-snmp/proc.h
./mib_modules.lo: mibgroup/ucd-snmp/versioninfo.h mibgroup/ucd-snmp/pass.h
./mib_modules.lo: mibgroup/ucd-snmp/pass_persist.h mibgroup/ucd-snmp/disk.h
./mib_modules.lo: mibgroup/ucd-snmp/loadave.h mibgroup/ucd-snmp/extensible.h
./mib_modules.lo: mibgroup/ucd-snmp/errormib.h mibgroup/ucd-snmp/registry.h
./mib_modules.lo: mibgroup/ucd-snmp/file.h mibgroup/ucd-snmp/dlmod.h
./mib_modules.lo: mibgroup/ucd-snmp/proxy.h mibgroup/snmpv3/snmpEngine.h
./mib_modules.lo: mibgroup/snmpv3/snmpMPDStats.h mibgroup/snmpv3/usmStats.h
./mib_modules.lo: mibgroup/snmpv3/usmUser.h ../include/net-snmp/snmpusm.h
./mib_modules.lo: mibgroup/notification/snmpNotifyTable.h
./mib_modules.lo: mibgroup/notification/snmpNotifyFilterTable.h
./mib_modules.lo: mibgroup/notification/snmpNotifyFilterProfileTable.h
./mib_modules.lo: mibgroup/agentx/master.h mibgroup/agentx/subagent.h
./mib_modules.lo: mibgroup/util_funcs.h mibgroup/struct.h
./mib_modules.lo: mibgroup/policy/policyEndpointToGroupTable.h
./mib_modules.lo: mibgroup/policy/policyGroupContentsTable.h
./mib_modules.lo: mibgroup/policy/policyRuleDefinitionTable.h
./mib_modules.lo: mibgroup/policy/conditionsInRuleTable.h
./mib_modules.lo: mibgroup/policy/conditionTable.h
./mib_modules.lo: mibgroup/policy/filtersInConditionTable.h
./mib_modules.lo: mibgroup/policy/filterTable.h
./mib_modules.lo: mibgroup/policy/saStaticActionTable.h
./mib_modules.lo: mibgroup/host/hr_system.h mibgroup/host/hr_storage.h
./mib_modules.lo: mibgroup/host/hr_device.h mibgroup/host/hr_other.h
./mib_modules.lo: mibgroup/host/hr_proc.h mibgroup/host/hr_network.h
./mib_modules.lo: mibgroup/host/hr_print.h mibgroup/host/hr_disk.h
./mib_modules.lo: mibgroup/host/hr_partition.h mibgroup/host/hr_filesys.h
./mib_modules.lo: mibgroup/host/hr_swrun.h mibgroup/host/hr_swinst.h
./mib_modules.lo: mibgroup/mibII/kernel_linux.h mibgroup/mibII/tcpTable.h
./mib_modules.lo: mibgroup/mibII/ipAddr.h mibgroup/mibII/var_route.h
./mib_modules.lo: mibgroup/mibII/route_write.h mibgroup/mibII/udpTable.h
./mib_modules.lo: mibgroup/mibII/vacm_context.h mibgroup/header_complex.h
./mib_modules.lo: mibgroup/target.h mibgroup/agentx/protocol.h
./mib_modules.lo: mibgroup/agentx/client.h mibgroup/agentx/master_admin.h
./mib_modules.lo: mibgroup/agentx/agentx_config.h
./mib_modules.lo: mibgroup/policy/policy_iterator.h
./mib_modules.lo: mibgroup/target/snmpTargetAddrEntry.h
./mib_modules.lo: mibgroup/target/snmpTargetParamsEntry.h
./mib_modules.lo: mibgroup/target/target.h mibgroup/target/target_counters.h
./mib_modules.lo: ./mibgroup/mib_module_inits.h
./snmp_agent.lo: ../include/net-snmp/net-snmp-config.h
./snmp_agent.lo: ../include/net-snmp/system/linux.h
./snmp_agent.lo: ../include/net-snmp/system/sysv.h
./snmp_agent.lo: ../include/net-snmp/system/generic.h
./snmp_agent.lo: ../include/net-snmp/machine/generic.h
./snmp_agent.lo: ./mibgroup/mibincl.h 
./snmp_agent.lo: ../include/net-snmp/asn1.h ../include/net-snmp/snmp_api.h
./snmp_agent.lo: ../include/net-snmp/snmp_impl.h
./snmp_agent.lo: ../include/net-snmp/snmp_client.h
./snmp_agent.lo: ../include/net-snmp/agent/snmp_vars.h
./snmp_agent.lo: ../include/net-snmp/agent/agent_registry.h
./snmp_agent.lo: ../include/net-snmp/agent/snmp_agent.h
./snmp_agent.lo: ../include/net-snmp/tools.h ../include/net-snmp/data_list.h
./snmp_agent.lo: ../include/net-snmp/snmp_impl.h ../include/net-snmp/tools.h
./snmp_agent.lo: ../include/net-snmp/agent/agent_read_config.h
./snmp_agent.lo: ../include/net-snmp/agent/agent_handler.h
./snmp_agent.lo: ../include/net-snmp/agent/agent_registry.h
./snmp_agent.lo: ../include/net-snmp/agent/var_struct.h
./snmp_agent.lo: ../include/net-snmp/snmp.h ../include/net-snmp/mib.h
./snmp_agent.lo: ../include/net-snmp/snmp_debug.h
./snmp_agent.lo: ../include/net-snmp/snmp_logging.h 
./snmp_agent.lo:  ../include/net-snmp/snmp_alarm.h
./snmp_agent.lo: ../include/net-snmp/read_config.h
./snmp_agent.lo: ../include/net-snmp/agent/agent_trap.h
./snmp_agent.lo: ../include/net-snmp/callback.h snmpd.h mibgroup/struct.h
./snmp_agent.lo: mibgroup/util_funcs.h mibgroup/struct.h
./snmp_agent.lo: ../include/net-snmp/default_store.h
./snmp_agent.lo: ../include/net-snmp/system.h
./snmp_agent.lo: ../include/net-snmp/agent/ds_agent.h
./snmp_agent.lo: ../include/net-snmp/agent/snmp_agent.h
./snmp_agent.lo: ../include/net-snmp/snmp_transport.h
./snmp_agent.lo: ../include/net-snmp/asn1.h ../include/net-snmp/vacm.h
./snmpd.lo: ../include/net-snmp/net-snmp-config.h
./snmpd.lo: ../include/net-snmp/system/linux.h
./snmpd.lo: ../include/net-snmp/system/sysv.h
./snmpd.lo: ../include/net-snmp/system/generic.h
./snmpd.lo: ../include/net-snmp/machine/generic.h 
./snmpd.lo: ../include/net-snmp/asn1.h ../include/net-snmp/snmp_api.h
./snmpd.lo: ../include/net-snmp/snmp_impl.h ../include/net-snmp/system.h
./snmpd.lo: ../include/net-snmp/read_config.h ../include/net-snmp/snmp.h
./snmpd.lo: ../include/net-snmp/mib.h m2m.h
./snmpd.lo: ../include/net-snmp/agent/snmp_vars.h
./snmpd.lo: ../include/net-snmp/agent/agent_registry.h
./snmpd.lo: ../include/net-snmp/agent/snmp_agent.h
./snmpd.lo: ../include/net-snmp/tools.h ../include/net-snmp/data_list.h
./snmpd.lo: ../include/net-snmp/snmp_impl.h ../include/net-snmp/tools.h
./snmpd.lo: ../include/net-snmp/agent/agent_read_config.h
./snmpd.lo: ../include/net-snmp/snmpv3.h ../include/net-snmp/callback.h
./snmpd.lo: ../include/net-snmp/snmp_alarm.h
./snmpd.lo: ../include/net-snmp/default_store.h
./snmpd.lo: ../include/net-snmp/snmp_client.h snmpd.h
./snmpd.lo: ../include/net-snmp/agent/agent_handler.h
./snmpd.lo: ../include/net-snmp/agent/var_struct.h mibgroup/struct.h
./snmpd.lo: ../include/net-snmp/snmp_debug.h
./snmpd.lo: ../include/net-snmp/agent/mib_modules.h
./snmpd.lo: ../include/net-snmp/snmp_secmod.h ../include/net-snmp/snmpusm.h
./snmpd.lo: ../include/net-snmp/lcd_time.h mibgroup/util_funcs.h
./snmpd.lo: mibgroup/struct.h ../include/net-snmp/agent/snmp_agent.h
./snmpd.lo: ../include/net-snmp/agent/agent_trap.h
./snmpd.lo: ../include/net-snmp/agent/ds_agent.h
./snmpd.lo: ../include/net-snmp/snmp_logging.h 
./snmpd.lo:  ../include/net-snmp/snmp_transport.h
./snmpd.lo: ../include/net-snmp/asn1.h ../include/net-snmp/version.h
./snmpd.lo: ../include/net-snmp/agent/table.h
./snmpd.lo: ../include/net-snmp/agent/table_iterator.h
./snmpd.lo: ./mibgroup/mib_module_includes.h mibgroup/mibII.h
./snmpd.lo: mibgroup/ucd_snmp.h mibgroup/snmpv3mibs.h mibgroup/notification.h
./snmpd.lo: mibgroup/agentx.h mibgroup/agent_mibs.h mibgroup/testhandler.h
./snmpd.lo: mibgroup/testdelayed.h mibgroup/examples/example.h
./snmpd.lo: mibgroup/agent/nsTransactionTable.h mibgroup/policy.h
./snmpd.lo: mibgroup/host.h mibgroup/mibII/system_mib.h
./snmpd.lo: mibgroup/mibII/sysORTable.h mibgroup/mibII/at.h
./snmpd.lo: mibgroup/mibII/interfaces.h mibgroup/mibII/snmp_mib.h
./snmpd.lo: mibgroup/mibII/tcp.h mibgroup/mibII/icmp.h mibgroup/mibII/ip.h
./snmpd.lo: mibgroup/mibII/var_route.h mibgroup/mibII/route_write.h
./snmpd.lo: mibgroup/mibII/udp.h mibgroup/mibII/vacm_vars.h
./snmpd.lo: ../include/net-snmp/vacm.h mibgroup/ucd-snmp/memory.h
./snmpd.lo: ./mibgroup/mibdefs.h mibgroup/ucd-snmp/vmstat.h
./snmpd.lo: mibgroup/ucd-snmp/proc.h mibgroup/ucd-snmp/versioninfo.h
./snmpd.lo: mibgroup/ucd-snmp/pass.h mibgroup/ucd-snmp/pass_persist.h
./snmpd.lo: mibgroup/ucd-snmp/disk.h mibgroup/ucd-snmp/loadave.h
./snmpd.lo: mibgroup/ucd-snmp/extensible.h mibgroup/ucd-snmp/errormib.h
./snmpd.lo: mibgroup/ucd-snmp/registry.h mibgroup/ucd-snmp/file.h
./snmpd.lo: mibgroup/ucd-snmp/dlmod.h mibgroup/ucd-snmp/proxy.h
./snmpd.lo: mibgroup/snmpv3/snmpEngine.h mibgroup/snmpv3/snmpMPDStats.h
./snmpd.lo: mibgroup/snmpv3/usmStats.h mibgroup/snmpv3/usmUser.h
./snmpd.lo: mibgroup/notification/snmpNotifyTable.h
./snmpd.lo: mibgroup/notification/snmpNotifyFilterTable.h
./snmpd.lo: mibgroup/notification/snmpNotifyFilterProfileTable.h
./snmpd.lo: mibgroup/agentx/master.h mibgroup/agentx/subagent.h
./snmpd.lo: mibgroup/policy/policyEndpointToGroupTable.h
./snmpd.lo: mibgroup/policy/policyGroupContentsTable.h
./snmpd.lo: mibgroup/policy/policyRuleDefinitionTable.h
./snmpd.lo: mibgroup/policy/conditionsInRuleTable.h
./snmpd.lo: mibgroup/policy/conditionTable.h
./snmpd.lo: mibgroup/policy/filtersInConditionTable.h
./snmpd.lo: mibgroup/policy/filterTable.h
./snmpd.lo: mibgroup/policy/saStaticActionTable.h mibgroup/host/hr_system.h
./snmpd.lo: mibgroup/host/hr_storage.h mibgroup/host/hr_device.h
./snmpd.lo: mibgroup/host/hr_other.h mibgroup/host/hr_proc.h
./snmpd.lo: mibgroup/host/hr_network.h mibgroup/host/hr_print.h
./snmpd.lo: mibgroup/host/hr_disk.h mibgroup/host/hr_partition.h
./snmpd.lo: mibgroup/host/hr_filesys.h mibgroup/host/hr_swrun.h
./snmpd.lo: mibgroup/host/hr_swinst.h mibgroup/mibII/kernel_linux.h
./snmpd.lo: mibgroup/mibII/tcpTable.h mibgroup/mibII/ipAddr.h
./snmpd.lo: mibgroup/mibII/var_route.h mibgroup/mibII/route_write.h
./snmpd.lo: mibgroup/mibII/udpTable.h mibgroup/mibII/vacm_context.h
./snmpd.lo: mibgroup/header_complex.h mibgroup/target.h
./snmpd.lo: mibgroup/agentx/protocol.h mibgroup/agentx/client.h
./snmpd.lo: mibgroup/agentx/master_admin.h mibgroup/agentx/agentx_config.h
./snmpd.lo: mibgroup/policy/policy_iterator.h
./snmpd.lo: mibgroup/target/snmpTargetAddrEntry.h
./snmpd.lo: mibgroup/target/snmpTargetParamsEntry.h mibgroup/target/target.h
./snmpd.lo: mibgroup/target/target_counters.h
./snmpd.lo: ./mibgroup/mib_module_shutdown.h
./snmp_perl.lo: ../include/net-snmp/net-snmp-config.h
./snmp_perl.lo: ../include/net-snmp/system/linux.h
./snmp_perl.lo: ../include/net-snmp/system/sysv.h
./snmp_perl.lo: ../include/net-snmp/system/generic.h
./snmp_perl.lo: ../include/net-snmp/machine/generic.h
./snmp_perl.lo: ../include/net-snmp/net-snmp-includes.h
./snmp_perl.lo: ../include/net-snmp/net-snmp-config.h 
./snmp_perl.lo: ../include/net-snmp/definitions.h ../include/net-snmp/types.h
./snmp_perl.lo: ../include/net-snmp/snmp_api.h
./snmp_perl.lo: ../include/net-snmp/session_api.h
./snmp_perl.lo: ../include/net-snmp/snmp_client.h ../include/net-snmp/asn1.h
./snmp_perl.lo: ../include/net-snmp/callback.h
./snmp_perl.lo: ../include/net-snmp/snmp_transport.h
./snmp_perl.lo: ../include/net-snmp/asn1.h
./snmp_perl.lo: ../include/net-snmp/snmpCallbackDomain.h
./snmp_perl.lo: ../include/net-snmp/snmp_transport.h
./snmp_perl.lo: ../include/net-snmp/snmpUnixDomain.h
./snmp_perl.lo: ../include/net-snmp/snmpUDPDomain.h
./snmp_perl.lo: ../include/net-snmp/snmpTCPDomain.h
./snmp_perl.lo: ../include/net-snmp/pdu_api.h ../include/net-snmp/mib_api.h
./snmp_perl.lo: ../include/net-snmp/mib.h ../include/net-snmp/parse.h
./snmp_perl.lo: ../include/net-snmp/oid_array.h
./snmp_perl.lo: ../include/net-snmp/oid_stash.h
./snmp_perl.lo: ../include/net-snmp/varbind_api.h
./snmp_perl.lo: ../include/net-snmp/config_api.h
./snmp_perl.lo: ../include/net-snmp/read_config.h
./snmp_perl.lo: ../include/net-snmp/default_store.h
./snmp_perl.lo: ../include/net-snmp/snmp_parse_args.h
./snmp_perl.lo: ../include/net-snmp/snmp_enum.h ../include/net-snmp/vacm.h
./snmp_perl.lo: ../include/net-snmp/logging_api.h
./snmp_perl.lo: ../include/net-snmp/snmp_debug.h
./snmp_perl.lo: ../include/net-snmp/snmp_logging.h 
./snmp_perl.lo:  ../include/net-snmp/utilities.h
./snmp_perl.lo: ../include/net-snmp/getopt.h ../include/net-snmp/system.h
./snmp_perl.lo: ../include/net-snmp/tools.h ../include/net-snmp/int64.h
./snmp_perl.lo: ../include/net-snmp/mt_support.h
./snmp_perl.lo: ../include/net-snmp/snmp_locking.h
./snmp_perl.lo: ../include/net-snmp/snmp_alarm.h
./snmp_perl.lo: ../include/net-snmp/data_list.h
./snmp_perl.lo: ../include/net-snmp/snmp_impl.h ../include/net-snmp/tools.h
./snmp_perl.lo: ../include/net-snmp/snmp.h ../include/net-snmp/snmp_impl.h
./snmp_perl.lo: ../include/net-snmp/snmp-tc.h ../include/net-snmp/version.h
./snmp_perl.lo: ../include/net-snmp/snmpv3_api.h ../include/net-snmp/snmpv3.h
./snmp_perl.lo: ../include/net-snmp/transform_oids.h
./snmp_perl.lo: ../include/net-snmp/keytools.h ../include/net-snmp/scapi.h
./snmp_perl.lo: ../include/net-snmp/lcd_time.h ../include/net-snmp/md5.h
./snmp_perl.lo: ../include/net-snmp/snmp_secmod.h
./snmp_perl.lo: ../include/net-snmp/snmpksm.h ../include/net-snmp/snmpusm.h
./snmp_perl.lo: ../include/net-snmp/agent/net-snmp-agent-includes.h
./snmp_perl.lo: ../include/net-snmp/agent/snmp_agent.h
./snmp_perl.lo: ../include/net-snmp/agent/snmp_vars.h
./snmp_perl.lo: ../include/net-snmp/agent/agent_registry.h
./snmp_perl.lo: ../include/net-snmp/agent/snmp_agent.h
./snmp_perl.lo: ../include/net-snmp/agent/ds_agent.h
./snmp_perl.lo: ../include/net-snmp/agent/agent_handler.h
./snmp_perl.lo: ../include/net-snmp/agent/var_struct.h
./snmp_perl.lo: ../include/net-snmp/agent/agent_read_config.h
./snmp_vars.lo: ../include/net-snmp/net-snmp-config.h
./snmp_vars.lo:  ./mibgroup/mibincl.h
./snmp_vars.lo:  ../include/net-snmp/asn1.h
./snmp_vars.lo: ../include/net-snmp/snmp_api.h
./snmp_vars.lo: ../include/net-snmp/snmp_impl.h
./snmp_vars.lo: ../include/net-snmp/snmp_client.h
./snmp_vars.lo: ../include/net-snmp/agent/snmp_vars.h
./snmp_vars.lo: ../include/net-snmp/agent/agent_registry.h
./snmp_vars.lo: ../include/net-snmp/agent/snmp_agent.h
./snmp_vars.lo: ../include/net-snmp/tools.h ../include/net-snmp/data_list.h
./snmp_vars.lo: ../include/net-snmp/snmp_impl.h ../include/net-snmp/tools.h
./snmp_vars.lo: ../include/net-snmp/agent/agent_read_config.h
./snmp_vars.lo: ../include/net-snmp/agent/agent_handler.h
./snmp_vars.lo: ../include/net-snmp/agent/agent_registry.h
./snmp_vars.lo: ../include/net-snmp/agent/var_struct.h
./snmp_vars.lo: ../include/net-snmp/snmp.h ../include/net-snmp/mib.h
./snmp_vars.lo: ../include/net-snmp/snmp_debug.h
./snmp_vars.lo: ../include/net-snmp/snmp_logging.h 
./snmp_vars.lo:  ../include/net-snmp/snmp_alarm.h
./snmp_vars.lo: ../include/net-snmp/read_config.h
./snmp_vars.lo: ../include/net-snmp/agent/agent_trap.h
./snmp_vars.lo: ../include/net-snmp/callback.h ../include/net-snmp/snmpv3.h
./snmp_vars.lo: ../include/net-snmp/snmp_secmod.h
./snmp_vars.lo: ../include/net-snmp/snmpusm.h ../include/net-snmp/system.h
./snmp_vars.lo: kernel.h ../include/net-snmp/default_store.h
./snmp_vars.lo: ../include/net-snmp/agent/ds_agent.h mibgroup/struct.h
./snmp_vars.lo: ../include/net-snmp/transform_oids.h snmpd.h
./snmp_vars.lo: ../include/net-snmp/agent/all_helpers.h
./snmp_vars.lo: ../include/net-snmp/agent/instance.h
./snmp_vars.lo: ../include/net-snmp/agent/multiplexer.h
./snmp_vars.lo: ../include/net-snmp/agent/null.h
./snmp_vars.lo: ../include/net-snmp/agent/debug_handler.h
./snmp_vars.lo: ../include/net-snmp/agent/old_api.h
./snmp_vars.lo: ../include/net-snmp/agent/read_only.h
./snmp_vars.lo: ../include/net-snmp/agent/serialize.h
./snmp_vars.lo: ../include/net-snmp/agent/bulk_to_next.h
./snmp_vars.lo: ../include/net-snmp/agent/table.h
./snmp_vars.lo: ../include/net-snmp/agent/table_data.h
./snmp_vars.lo: ../include/net-snmp/agent/table_dataset.h
./snmp_vars.lo: ../include/net-snmp/agent/table_iterator.h
./snmp_vars.lo: ./mibgroup/mib_module_includes.h mibgroup/mibII.h
./snmp_vars.lo: mibgroup/ucd_snmp.h mibgroup/snmpv3mibs.h
./snmp_vars.lo: mibgroup/notification.h mibgroup/agentx.h
./snmp_vars.lo: mibgroup/agent_mibs.h mibgroup/testhandler.h
./snmp_vars.lo: mibgroup/testdelayed.h mibgroup/examples/example.h
./snmp_vars.lo: mibgroup/agent/nsTransactionTable.h mibgroup/policy.h
./snmp_vars.lo: mibgroup/host.h mibgroup/mibII/system_mib.h
./snmp_vars.lo: mibgroup/mibII/sysORTable.h mibgroup/mibII/at.h
./snmp_vars.lo: mibgroup/mibII/interfaces.h mibgroup/mibII/snmp_mib.h
./snmp_vars.lo: mibgroup/mibII/tcp.h mibgroup/mibII/icmp.h
./snmp_vars.lo: mibgroup/mibII/ip.h mibgroup/mibII/var_route.h
./snmp_vars.lo: mibgroup/mibII/route_write.h mibgroup/mibII/udp.h
./snmp_vars.lo: mibgroup/mibII/vacm_vars.h ../include/net-snmp/vacm.h
./snmp_vars.lo: mibgroup/ucd-snmp/memory.h ./mibgroup/mibdefs.h
./snmp_vars.lo: mibgroup/ucd-snmp/vmstat.h mibgroup/ucd-snmp/proc.h
./snmp_vars.lo: mibgroup/ucd-snmp/versioninfo.h mibgroup/ucd-snmp/pass.h
./snmp_vars.lo: mibgroup/ucd-snmp/pass_persist.h mibgroup/ucd-snmp/disk.h
./snmp_vars.lo: mibgroup/ucd-snmp/loadave.h mibgroup/ucd-snmp/extensible.h
./snmp_vars.lo: mibgroup/ucd-snmp/errormib.h mibgroup/ucd-snmp/registry.h
./snmp_vars.lo: mibgroup/ucd-snmp/file.h mibgroup/ucd-snmp/dlmod.h
./snmp_vars.lo: mibgroup/ucd-snmp/proxy.h mibgroup/snmpv3/snmpEngine.h
./snmp_vars.lo: mibgroup/snmpv3/snmpMPDStats.h mibgroup/snmpv3/usmStats.h
./snmp_vars.lo: mibgroup/snmpv3/usmUser.h
./snmp_vars.lo: mibgroup/notification/snmpNotifyTable.h
./snmp_vars.lo: mibgroup/notification/snmpNotifyFilterTable.h
./snmp_vars.lo: mibgroup/notification/snmpNotifyFilterProfileTable.h
./snmp_vars.lo: mibgroup/agentx/master.h mibgroup/agentx/subagent.h
./snmp_vars.lo: mibgroup/util_funcs.h mibgroup/struct.h
./snmp_vars.lo: mibgroup/policy/policyEndpointToGroupTable.h
./snmp_vars.lo: mibgroup/policy/policyGroupContentsTable.h
./snmp_vars.lo: mibgroup/policy/policyRuleDefinitionTable.h
./snmp_vars.lo: mibgroup/policy/conditionsInRuleTable.h
./snmp_vars.lo: mibgroup/policy/conditionTable.h
./snmp_vars.lo: mibgroup/policy/filtersInConditionTable.h
./snmp_vars.lo: mibgroup/policy/filterTable.h
./snmp_vars.lo: mibgroup/policy/saStaticActionTable.h
./snmp_vars.lo: mibgroup/host/hr_system.h mibgroup/host/hr_storage.h
./snmp_vars.lo: mibgroup/host/hr_device.h mibgroup/host/hr_other.h
./snmp_vars.lo: mibgroup/host/hr_proc.h mibgroup/host/hr_network.h
./snmp_vars.lo: mibgroup/host/hr_print.h mibgroup/host/hr_disk.h
./snmp_vars.lo: mibgroup/host/hr_partition.h mibgroup/host/hr_filesys.h
./snmp_vars.lo: mibgroup/host/hr_swrun.h mibgroup/host/hr_swinst.h
./snmp_vars.lo: mibgroup/mibII/kernel_linux.h mibgroup/mibII/tcpTable.h
./snmp_vars.lo: mibgroup/mibII/ipAddr.h mibgroup/mibII/var_route.h
./snmp_vars.lo: mibgroup/mibII/route_write.h mibgroup/mibII/udpTable.h
./snmp_vars.lo: mibgroup/mibII/vacm_context.h mibgroup/header_complex.h
./snmp_vars.lo: mibgroup/target.h mibgroup/agentx/protocol.h
./snmp_vars.lo: mibgroup/agentx/client.h mibgroup/agentx/master_admin.h
./snmp_vars.lo: mibgroup/agentx/agentx_config.h
./snmp_vars.lo: mibgroup/policy/policy_iterator.h
./snmp_vars.lo: mibgroup/target/snmpTargetAddrEntry.h
./snmp_vars.lo: mibgroup/target/snmpTargetParamsEntry.h
./snmp_vars.lo: mibgroup/target/target.h mibgroup/target/target_counters.h
