#!/bin/sh

. ../support/simple_eval_tools.sh

HEADER "snmpv3 dynamic and static informs are sent by snmpd API"

SKIPIFNOT NETSNMP_SECMOD_USM
SKIPIFNOT USING_EXAMPLES_EXAMPLE_MODULE

NOTIFYTYPE=inform
TRAPSESS=yes
DYNTRAP=yes

#
# Begin test
#

. ./Sv3usmtraps
