#!/bin/sh

. ../support/simple_eval_tools.sh

HEADER "snmpv3 static traps are sent by snmpd API"

SKIPIFNOT NETSNMP_SECMOD_USM
SKIPIFNOT USING_EXAMPLES_EXAMPLE_MODULE

NOTIFYTYPE="trap"
TRAPSESS="yes"
DYNTRAP="no"

#
# Begin test
#

. ./Sv3usmtraps
