#!/bin/sh

. ../support/simple_eval_tools.sh

HEADER snmpv1 traps are sent by snmpd API

SKIPIFNOT USING_EXAMPLES_EXAMPLE_MODULE
SKIPIFNOT HAVE_SIGHUP

SKIPIF NETSNMP_DISABLE_SET_SUPPORT
SKIPIF NETSNMP_NO_WRITE_SUPPORT

#
# Begin test
#

# standard V1 configuration: testcomunnity
. ./Sv3config

CONFIGTRAPD authcommunity log public
CONFIGTRAPD agentxsocket /dev/null

STARTTRAPD

CONFIGAGENT trapsink ${SNMP_TRANSPORT_SPEC}:${SNMP_TEST_DEST}${SNMP_SNMPTRAPD_PORT} public

AGENT_FLAGS="$AGENT_FLAGS -Dexample,header_generic,add_trap"
STARTAGENT

CAPTURE "snmpset -On $SNMP_FLAGS $AUTHTESTARGS $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPD_PORT .1.3.6.1.4.1.2021.254.7.0 i 1"

STOPAGENT

STOPTRAPD

CHECKTRAPD "Enterprise Specific Trap (99)"

FINISHED
