#!/bin/sh

. ../support/simple_eval_tools.sh

HEADER trap forwarding loops are detected by snmptrapd

SKIPIFNOT USING_EXAMPLES_EXAMPLE_MODULE
SKIPIFNOT HAVE_SIGHUP

SKIPIF NETSNMP_DISABLE_SET_SUPPORT
SKIPIF NETSNMP_NO_WRITE_SUPPORT

#
# Begin test
#

# standard V1 configuration: testcomunnity
. ./Sv3config

CONFIGTRAPD authcommunity log,execute,net public
CONFIGTRAPD agentxsocket /dev/null
CONFIGTRAPD addForwarderInfo yes

STARTTRAPD

CONFIGTRAPD forward default 127.0.0.1:${SNMP_SNMPTRAPD_PORT}
HUPPROG $SNMP_SNMPTRAPD_PID_FILE

CONFIGAGENT trapsink ${SNMP_TRANSPORT_SPEC}:${SNMP_TEST_DEST}${SNMP_SNMPTRAPD_PORT} public

AGENT_FLAGS="$AGENT_FLAGS -Dexample,header_generic,add_trap"
STARTAGENT

CAPTURE "snmpset -On $SNMP_FLAGS $AUTHTESTARGS $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPD_PORT .1.3.6.1.4.1.2021.254.7.0 i 1"

STOPAGENT

STOPTRAPD

CHECKAGENT "write_exampletrap trap sent"
CHECKTRAPDCOUNT 3 "Forwarding loop detected,.*already has.*IP address=127.0.0.1, not forwarding this trap"

FINISHED
