#!/bin/sh

. ../support/simple_eval_tools.sh

HEADER Agent uses -s argument for v6 trapsess source

SKIPIF NETSNMP_DISABLE_SNMPV2C

. ./S180trapaddrinfra

INITV6

CONFIGAGENT trapsess -s ${SNMP_AGENT_ADDR} -v 2c -c public ${SNMP_TRANSPORT_SPEC}:${SNMP_TEST_DEST}${SNMP_SNMPTRAPD_PORT}

RUNTEST
