environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      BUILD: MSVCDYNAMIC64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      BUILD: MSVCSTATIC64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      BUILD: INSTALLER
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      BUILD: MSYS2
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      BUILD: MinGW64
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-monterey
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204

artifacts:
  - path: installer

clone_depth: 5

install:
  - sh:  'sudo ci/install.sh'

build_script:
  - cmd: 'ci\build.bat'
  - sh:  'ci/build.sh'

test_script:
  - cmd: 'ci\test.bat'
  - sh:  'sudo -E ci/test.sh'
