table_dataset
NAME
table_dataset - Helps you implement a table with automatted storage.
Functions
void netsnmp_init_table_dataset (void)
netsnmp_table_data_set * netsnmp_create_table_data_set (const char *table_name)
Create a netsnmp_table_data_set structure given a table_data definition.
netsnmp_mib_handler * netsnmp_get_table_data_set_handler (netsnmp_table_data_set *data_set)
Given a netsnmp_table_data_set definition, create a handler for it.
int netsnmp_register_table_data_set (netsnmp_handler_registration *reginfo, netsnmp_table_data_set *data_set, netsnmp_table_registration_info *table_info)
register a given data_set at a given oid (specified in the netsnmp_handler_registration pointer).
netsnmp_table_data_set_storage * netsnmp_table_data_set_find_column (netsnmp_table_data_set_storage *start, unsigned int column)
Finds a column within a given storage set, given the pointer to the start of the storage set list.
netsnmp_table_data_set_storage * netsnmp_extract_table_data_set_column (netsnmp_request_info *request, unsigned int column)
extracts a netsnmp_table_data_set pointer from a given request
NETSNMP_INLINE netsnmp_table_data_set * netsnmp_extract_table_data_set (netsnmp_request_info *request)
extracts a netsnmp_table_data_set pointer from a given request
int netsnmp_mark_row_column_writable (netsnmp_table_row *row, int column, int writable)
marks a given column in a row as writable or not.
int netsnmp_set_row_column (netsnmp_table_row *row, unsigned int column, int type, const char *value, size_t value_len)
sets a given column in a row with data given a type, value, and length.
int netsnmp_table_set_add_default_row (netsnmp_table_data_set *table_set, unsigned int column, int type, int writable, void *default_value, size_t default_value_len)
adds a new default row to a table_set.
netsnmp_table_row * netsnmp_table_data_set_clone_row (netsnmp_table_row *row)
clones a dataset row, including all data.
netsnmp_table_row * netsnmp_table_data_set_create_row_from_defaults (netsnmp_table_data_set_storage *defrow)
creates a new row from an existing defined default set
newrow_stash * netsnmp_table_data_set_create_newrowstash (netsnmp_table_data_set *datatable, netsnmp_table_request_info *table_info)
int netsnmp_table_data_set_helper_handler (netsnmp_mib_handler *handler, netsnmp_handler_registration *reginfo, netsnmp_agent_request_info *reqinfo, netsnmp_request_info *requests)
implements the table data helper.
void netsnmp_register_auto_data_table (netsnmp_table_data_set *table_set, char *registration_name)
registers a table_dataset so that the 'add_row' snmpd.conf token can be used to add data to this table.
void netsnmp_config_parse_table_set (const char *token, char *line)
void netsnmp_config_parse_add_row (const char *token, char *line)
NETSNMP_INLINE void netsnmp_table_dataset_add_index (netsnmp_table_data_set *table, u_char type)
adds an index to the table.
NETSNMP_INLINE void netsnmp_table_dataset_add_row (netsnmp_table_data_set *table, netsnmp_table_row *row)
adds a new row to a dataset table
NETSNMP_INLINE void netsnmp_table_dataset_replace_row (netsnmp_table_data_set *table, netsnmp_table_row *origrow, netsnmp_table_row *newrow)
adds a new row to a dataset table
NETSNMP_INLINE netsnmp_table_data_set_storage * netsnmp_table_dataset_delete_data (netsnmp_table_data_set_storage *data)
deletes a single dataset table data.
NETSNMP_INLINE void netsnmp_table_dataset_delete_all_data (netsnmp_table_data_set_storage *data)
deletes all the data from this node and beyond in the linked list
NETSNMP_INLINE void netsnmp_table_dataset_delete_row (netsnmp_table_row *row)
deletes all the data from this node and beyond in the linked list
NETSNMP_INLINE void netsnmp_table_dataset_remove_row (netsnmp_table_data_set *table, netsnmp_table_row *row)
removes a row from the table, but doesn't delete/free the column values
NETSNMP_INLINE void netsnmp_table_dataset_remove_and_delete_row (netsnmp_table_data_set *table, netsnmp_table_row *row)
removes a row from the table and then deletes it (and all its data)
void netsnmp_table_set_multi_add_default_row (va_dcl)
adds multiple data column definitions to each row.
void netsnmp_table_set_add_indexes (va_alist)
adds multiple indexes to a table_dataset helper object.
int netsnmp_table_set_num_rows (netsnmp_table_data_set *table)
Variables
size_t data_set_cache_s::data_len
int newrow_stash_s::state
int newrow_stash_s::created
int newrow_stash_s::deleted
Detailed Description
Helps you implement a table with automatted storage.
This handler helps you implement a table where all the data is expected to be stored within the agent itself and not in some external storage location. It handles all MIB requests including GETs, GETNEXTs and SETs. It's possible to simply create a table without actually ever defining a handler to be called when SNMP requests come in. To use the data, you can either attach a sub-handler that merely uses/manipulates the data further when requests come in, or you can loop through it externally when it's actually needed. This handler is most useful in cases where a table is holding configuration data for something which gets triggered via another event.
NOTE NOTE NOTE: This helper isn't complete and is likely to change somewhat over time. Specifically, the way it stores data internally may change drastically.
Function Documentation
netsnmp_table_data_set* netsnmp_create_table_data_set (const char * table_name)
Create a netsnmp_table_data_set structure given a table_data definition.
Examples:
data_set.c.
Definition at line 75 of file table_dataset.c.
References netsnmp_create_table_data(), NULL, SNMP_MALLOC_TYPEDEF, and netsnmp_table_data_set_s::table.
Referenced by netsnmp_config_parse_table_set().
NETSNMP_INLINE netsnmp_table_data_set* netsnmp_extract_table_data_set (netsnmp_request_info * request)
extracts a netsnmp_table_data_set pointer from a given request
Definition at line 187 of file table_dataset.c.
References netsnmp_request_get_list_data().
netsnmp_table_data_set_storage* netsnmp_extract_table_data_set_column (netsnmp_request_info * request, unsigned int column)
extracts a netsnmp_table_data_set pointer from a given request
Definition at line 173 of file table_dataset.c.
References netsnmp_extract_table_row_data(), and netsnmp_table_data_set_find_column().
netsnmp_mib_handler* netsnmp_get_table_data_set_handler (netsnmp_table_data_set * data_set)
Given a netsnmp_table_data_set definition, create a handler for it.
Definition at line 87 of file table_dataset.c.
References netsnmp_mib_handler_s::myvoid, netsnmp_create_handler(), netsnmp_table_data_set_helper_handler(), NULL, and snmp_log().
Referenced by netsnmp_register_table_data_set().
int netsnmp_mark_row_column_writable (netsnmp_table_row * row, int column, int writable)
marks a given column in a row as writable or not.
Examples:
data_set.c.
Definition at line 197 of file table_dataset.c.
References netsnmp_table_data_set_storage_s::column, netsnmp_table_row_s::data, netsnmp_table_data_set_find_column(), netsnmp_table_data_set_storage_s::next, snmp_log(), SNMP_MALLOC_TYPEDEF, and netsnmp_table_data_set_storage_s::writable.
Referenced by netsnmp_config_parse_add_row(), and netsnmp_table_data_set_create_row_from_defaults().
void netsnmp_register_auto_data_table (netsnmp_table_data_set * table_set, char * registration_name)
registers a table_dataset so that the 'add_row' snmpd.conf token can be used to add data to this table.
If registration_name is NULL then the name used when the table was created will be used instead.
Todo
create a properly free'ing registeration pointer for the datalist, and get the datalist freed at shutdown.
Examples:
data_set.c.
Definition at line 783 of file table_dataset.c.
References netsnmp_table_data_s::name, netsnmp_add_list_data(), netsnmp_create_data_list(), NULL, SNMP_MALLOC_TYPEDEF, netsnmp_table_data_set_s::table, and data_set_tables_s::table_set.
Referenced by netsnmp_config_parse_table_set().
int netsnmp_register_table_data_set (netsnmp_handler_registration * reginfo, netsnmp_table_data_set * data_set, netsnmp_table_registration_info * table_info)
register a given data_set at a given oid (specified in the netsnmp_handler_registration pointer).
The reginfo->handler->access_method *may* be null if the call doesn't ever want to be called for SNMP operations.
Examples:
data_set.c.
Definition at line 113 of file table_dataset.c.
References netsnmp_table_data_set_storage_s::column, netsnmp_table_data_set_s::default_row, netsnmp_table_registration_info_s::indexes, netsnmp_table_data_s::indexes_template, netsnmp_table_registration_info_s::max_column, netsnmp_table_registration_info_s::min_column, netsnmp_get_table_data_set_handler(), netsnmp_inject_handler(), netsnmp_register_table_data(), netsnmp_table_data_set_storage_s::next, NULL, snmp_clone_varbind(), SNMP_MALLOC_TYPEDEF, SNMP_MAX, SNMP_MIN, and netsnmp_table_data_set_s::table.
Referenced by netsnmp_config_parse_table_set().
int netsnmp_set_row_column (netsnmp_table_row * row, unsigned int column, int type, const char * value, size_t value_len)
sets a given column in a row with data given a type, value, and length.
Data is memdup'ed by the function.
Examples:
data_set.c.
Definition at line 233 of file table_dataset.c.
References netsnmp_table_data_set_storage_s::column, netsnmp_table_row_s::data, netsnmp_table_data_set_storage_s::data, netsnmp_table_data_set_storage_s::data_len, memdup(), netsnmp_table_data_set_find_column(), netsnmp_table_data_set_storage_s::next, SNMP_FREE, snmp_log(), SNMP_MALLOC_TYPEDEF, and netsnmp_table_data_set_storage_s::type.
Referenced by netsnmp_config_parse_add_row(), and netsnmp_table_data_set_create_row_from_defaults().
netsnmp_table_row* netsnmp_table_data_set_clone_row (netsnmp_table_row * row)
clones a dataset row, including all data.
Definition at line 347 of file table_dataset.c.
References netsnmp_table_row_s::data, memdup(), netsnmp_table_data_clone_row(), netsnmp_table_dataset_delete_row(), netsnmp_table_data_set_storage_s::next, and NULL.
Referenced by netsnmp_table_data_set_helper_handler().
netsnmp_table_row* netsnmp_table_data_set_create_row_from_defaults (netsnmp_table_data_set_storage * defrow)
creates a new row from an existing defined default set
Definition at line 389 of file table_dataset.c.
References netsnmp_table_row_s::data, netsnmp_create_table_data_row(), netsnmp_mark_row_column_writable(), netsnmp_set_row_column(), and NULL.
Referenced by netsnmp_table_data_set_create_newrowstash().
netsnmp_table_data_set_storage* netsnmp_table_data_set_find_column (netsnmp_table_data_set_storage * start, unsigned int column)
Finds a column within a given storage set, given the pointer to the start of the storage set list.
Definition at line 161 of file table_dataset.c.
References netsnmp_table_data_set_storage_s::column, and netsnmp_table_data_set_storage_s::next.
Referenced by netsnmp_extract_table_data_set_column(), netsnmp_mark_row_column_writable(), netsnmp_set_row_column(), netsnmp_table_data_set_helper_handler(), and netsnmp_table_set_add_default_row().
int netsnmp_table_data_set_helper_handler (netsnmp_mib_handler * handler, netsnmp_handler_registration * reginfo, netsnmp_agent_request_info * reqinfo, netsnmp_request_info * requests)
implements the table data helper.
This is the routine that takes care of all SNMP requests coming into the table.
Definition at line 427 of file table_dataset.c.
References netsnmp_mib_handler_s::access_method, netsnmp_table_data_set_s::allow_creation, netsnmp_table_request_info_s::colnum, newrow_stash_s::created, netsnmp_table_data_set_storage_s::data, netsnmp_table_row_s::data, netsnmp_table_data_set_storage_s::data_len, newrow_stash_s::deleted, netsnmp_table_request_info_s::index_oid, netsnmp_table_request_info_s::index_oid_len, netsnmp_vardata::integer, netsnmp_agent_request_info_s::mode, netsnmp_mib_handler_s::myvoid, netsnmp_table_data_s::name, variable_list::name, variable_list::name_length, netsnmp_call_next_handler(), netsnmp_create_data_list(), netsnmp_extract_table_info(), netsnmp_extract_table_row(), netsnmp_oid_stash_add_data(), netsnmp_oid_stash_get_data(), netsnmp_request_add_list_data(), netsnmp_set_request_error(), netsnmp_strdup_and_null(), netsnmp_table_data_build_result(), netsnmp_table_data_set_clone_row(), netsnmp_table_data_set_create_newrowstash(), netsnmp_table_data_set_find_column(), netsnmp_table_dataset_add_row(), netsnmp_table_dataset_delete_row(), netsnmp_table_dataset_remove_and_delete_row(), netsnmp_table_dataset_replace_row(), newrow_stash_s::newrow, netsnmp_mib_handler_s::next, netsnmp_request_info_s::next, NULL, netsnmp_request_info_s::processed, netsnmp_request_info_s::requestvb, netsnmp_handler_registration_s::rootoid_len, netsnmp_table_data_set_s::rowstatus_column, SNMP_FREE, snmp_log(), SNMP_MALLOC_TYPEDEF, snprint_objid(), newrow_stash_s::state, netsnmp_vardata::string, netsnmp_table_data_set_s::table, variable_list::type, netsnmp_table_data_set_storage_s::type, variable_list::val, variable_list::val_len, and netsnmp_table_data_set_storage_s::writable.
Referenced by netsnmp_get_table_data_set_handler().
NETSNMP_INLINE void netsnmp_table_dataset_add_index (netsnmp_table_data_set * table, u_char type)
adds an index to the table.
Call this repeatly for each index.
Examples:
data_set.c.
Definition at line 1040 of file table_dataset.c.
References netsnmp_table_data_set_s::table.
Referenced by netsnmp_table_set_add_indexes().
NETSNMP_INLINE void netsnmp_table_dataset_add_row (netsnmp_table_data_set * table, netsnmp_table_row * row)
adds a new row to a dataset table
Examples:
data_set.c.
Definition at line 1049 of file table_dataset.c.
References netsnmp_table_data_add_row(), and netsnmp_table_data_set_s::table.
Referenced by netsnmp_table_data_set_helper_handler().
NETSNMP_INLINE void netsnmp_table_dataset_delete_all_data (netsnmp_table_data_set_storage * data)
deletes all the data from this node and beyond in the linked list
Definition at line 1085 of file table_dataset.c.
References netsnmp_table_dataset_delete_data().
Referenced by netsnmp_table_dataset_delete_row(), and netsnmp_table_dataset_remove_and_delete_row().
NETSNMP_INLINE netsnmp_table_data_set_storage* netsnmp_table_dataset_delete_data (netsnmp_table_data_set_storage * data)
deletes a single dataset table data.
returns the (possibly still good) next pointer of the deleted data object.
Definition at line 1072 of file table_dataset.c.
References netsnmp_table_data_set_storage_s::data, netsnmp_table_data_set_storage_s::next, NULL, and SNMP_FREE.
Referenced by netsnmp_table_dataset_delete_all_data().
NETSNMP_INLINE void netsnmp_table_dataset_delete_row (netsnmp_table_row * row)
deletes all the data from this node and beyond in the linked list
Definition at line 1095 of file table_dataset.c.
References netsnmp_table_data_delete_row(), and netsnmp_table_dataset_delete_all_data().
Referenced by netsnmp_table_data_set_clone_row(), and netsnmp_table_data_set_helper_handler().
NETSNMP_INLINE void netsnmp_table_dataset_remove_and_delete_row (netsnmp_table_data_set * table, netsnmp_table_row * row)
removes a row from the table and then deletes it (and all its data)
Definition at line 1119 of file table_dataset.c.
References netsnmp_table_data_remove_and_delete_row(), netsnmp_table_dataset_delete_all_data(), and netsnmp_table_data_set_s::table.
Referenced by netsnmp_table_data_set_helper_handler().
NETSNMP_INLINE void netsnmp_table_dataset_remove_row (netsnmp_table_data_set * table, netsnmp_table_row * row)
removes a row from the table, but doesn't delete/free the column values
Definition at line 1108 of file table_dataset.c.
References netsnmp_table_data_remove_and_delete_row(), and netsnmp_table_data_set_s::table.
NETSNMP_INLINE void netsnmp_table_dataset_replace_row (netsnmp_table_data_set * table, netsnmp_table_row * origrow, netsnmp_table_row * newrow)
adds a new row to a dataset table
Definition at line 1059 of file table_dataset.c.
References netsnmp_table_data_replace_row(), and netsnmp_table_data_set_s::table.
Referenced by netsnmp_table_data_set_helper_handler().
int netsnmp_table_set_add_default_row (netsnmp_table_data_set * table_set, unsigned int column, int type, int writable, void * default_value, size_t default_value_len)
adds a new default row to a table_set.
Arguments should be the table_set, column number, variable type and finally a 1 if it is allowed to be writable, or a 0 if not. If the default_value field is not NULL, it will be used to populate new valuse in that column fro newly created rows. It is copied into the storage template (free your calling argument).
returns SNMPERR_SUCCESS or SNMPERR_FAILURE
Definition at line 289 of file table_dataset.c.
References netsnmp_table_data_set_storage_s::column, netsnmp_table_data_set_storage_s::data, netsnmp_table_data_set_storage_s::data_len, netsnmp_table_data_set_s::default_row, memdup(), netsnmp_table_data_set_find_column(), netsnmp_table_data_set_storage_s::next, NULL, snmp_log(), SNMP_MALLOC_TYPEDEF, netsnmp_table_data_set_storage_s::type, and netsnmp_table_data_set_storage_s::writable.
Referenced by netsnmp_config_parse_table_set(), and netsnmp_table_set_multi_add_default_row().
void netsnmp_table_set_add_indexes (va_alist)
adds multiple indexes to a table_dataset helper object.
To end the list, use a 0 after the list of ASN index types.
Definition at line 1180 of file table_dataset.c.
References netsnmp_table_dataset_add_index().
void netsnmp_table_set_multi_add_default_row (va_dcl)
adds multiple data column definitions to each row.
Functionally, this is a wrapper around calling netsnmp_table_set_add_default_row repeatedly for you.
Examples:
data_set.c.
Definition at line 1141 of file table_dataset.c.
References netsnmp_table_set_add_default_row().