.TH "container" 3 "8 Apr 2008" "Version 5.2.4" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
container \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBnull_container\fP"
.br
.RI "\fIHelps you implement specialized containers
.PP
This is a simple container that doesn't actually contain anything. \fP"
.PP

.in -1c
