.TH "netsnmp_request_info_s" 3 "19 Mar 2004" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netsnmp_request_info_s \- The netsnmp request info structure. 
.SH SYNOPSIS
.br
.PP
\fC#include <snmp_agent.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "netsnmp_variable_list * \fBrequestvb\fP"
.br
.RI "\fIvariable bindings\fP"
.ti -1c
.RI "netsnmp_data_list * \fBparent_data\fP"
.br
.RI "\fIcan be used to pass information on a per-request basis from a helper to the later handlers\fP"
.ti -1c
.RI "oid * \fBrange_end\fP"
.br
.RI "\fIdon't free, reference to (struct tree)->end\fP"
.ti -1c
.RI "int \fBdelegated\fP"
.br
.RI "\fIflags\fP"
.ti -1c
.RI "int \fBindex\fP"
.br
.RI "\fIindex in original pdu\fP"
.ti -1c
.RI "int \fBrepeat\fP"
.br
.RI "\fIget-bulk\fP"
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
The netsnmp request info structure.
.PP
\fBExamples: \fP
.in +1c
.PP
\fBdelayed_instance.c\fP.
.PP
Definition at line 54 of file snmp_agent.h.
.SH "FIELD DOCUMENTATION"
.PP 
.SS "int netsnmp_request_info_s::delegated"
.PP
flags
.PP
\fBExamples: \fP
.in +1c
\fBdelayed_instance.c\fP.
.PP
Definition at line 76 of file snmp_agent.h.
.PP
Referenced by _request_set_error(), and netsnmp_handler_mark_requests_as_delegated().
.SS "int netsnmp_request_info_s::index"
.PP
index in original pdu
.PP
Definition at line 82 of file snmp_agent.h.
.PP
Referenced by check_getnext_results().
.SS "netsnmp_data_list* netsnmp_request_info_s::parent_data"
.PP
can be used to pass information on a per-request basis from a helper to the later handlers
.PP
Definition at line 64 of file snmp_agent.h.
.PP
Referenced by netsnmp_free_request_data_set(), netsnmp_free_request_data_sets(), netsnmp_request_add_list_data(), netsnmp_request_get_list_data(), and netsnmp_table_iterator_helper_handler().
.SS "oid* netsnmp_request_info_s::range_end"
.PP
don't free, reference to (struct tree)->end
.PP
Definition at line 72 of file snmp_agent.h.
.PP
Referenced by check_getnext_results().
.SS "int netsnmp_request_info_s::repeat"
.PP
get-bulk
.PP
Definition at line 85 of file snmp_agent.h.
.PP
Referenced by check_acm(), check_getnext_results(), and netsnmp_bulk_to_next_fix_requests().
.SS "netsnmp_variable_list* netsnmp_request_info_s::requestvb"
.PP
variable bindings
.PP
\fBExamples: \fP
.in +1c
\fBdelayed_instance.c\fP.
.PP
Definition at line 58 of file snmp_agent.h.
.PP
Referenced by _request_set_error(), check_acm(), check_getnext_results(), netsnmp_bulk_to_next_fix_requests(), netsnmp_check_getnext_reply(), netsnmp_old_api_helper(), netsnmp_row_merge_helper_handler(), netsnmp_table_build_oid(), netsnmp_table_build_oid_from_index(), netsnmp_table_build_result(), netsnmp_table_data_build_result(), netsnmp_table_data_helper_handler(), netsnmp_table_data_set_helper_handler(), netsnmp_table_iterator_helper_handler(), and table_helper_handler().

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
