.TH "leaf_handlers: process individual leaf objects" 3 "24 Jan 2005" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leaf_handlers: process individual leaf objects \- A group of handlers to implement individual leaf objects and instances (both scalar objects, and individual objects and instances within a table).  

.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "group\fBinstance: process individual MIB instances easily.\fP"
.br
.ti -1c
.RI "group\fBscalar: process scalars easily.\fP"
.br
.ti -1c
.RI "group\fBscalar_group: process groups of scalars.\fP"
.br
.ti -1c
.RI "group\fBwatcher: watch a specified variable and process\fP"
.br
.RI "\fIit as an instance or scalar object \fP"
.PP

.in -1c
.SH "Detailed Description"
.PP 
A group of handlers to implement individual leaf objects and instances (both scalar objects, and individual objects and instances within a table). These handlers will typically allow control to be passed down to a lower level, user-provided handler, but this is (usually) optional. 
