.TH "todo" 3 "27 Aug 2002" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List
.IP "Global \fBnetsnmp_table_get_or_create_row_stash\fP(netsnmp_agent_request_info *reqinfo, const u_char *storage_name) " 1c
 This function will likely change to add free pointer functions.
.PP
.IP "Global \fBnetsnmp_register_auto_data_table\fP(netsnmp_table_data_set *table_set, char *registration_name) " 1c
 create a properly free'ing registeration pointer for the datalist, and get the datalist freed at shutdown.  
