parsing various configuration files at run time
NAME
parsing various configuration files at run time - The read_config related functions are a fairly extensible system of parsing various configuration files at the run time.
Functions
config_line * register_config_handler (const char *type_param, const char *token, void(*parser)(const char *, char *), void(*releaser)(void), const char *help)
register_config_handler registers handlers for certain tokens specified in certain types of files.
void unregister_config_handler (const char *type_param, const char *token)
uregister_config_handler un-registers handlers given a specific type_param and token.
void read_config_store (const char *type, const char *line)
read_config_store intended for use by applications to store permenant configuration information generated by sets or persistent counters.
char * read_config_read_data (int type, char *readfrom, void *dataptr, size_t *len)
read_config_read_data reads data of a given type from a token(s) on a configuration line.
char * read_config_store_data (int type, char *storeto, void *dataptr, size_t *len)
read_config_store_data stores data of a given type to a configuration line into the storeto buffer.
DETAILED DESCRIPTION
The read_config related functions are a fairly extensible system of parsing various configuration files at the run time.
The idea is that the calling application is able to register handlers for certain tokens specified in certain types of files. The read_configs function can then be called to look for all the files that it has registrations for, find the first word on each line, and pass the remainder to the appropriately registered handler.
For persistent configuration storage you will need to use the read_config_read_data, read_config_store, and read_config_store_data APIs in conjunction with first registering a callback so when the agent shutsdown for whatever reason data is written to your configuration files. The following explains in more detail the sequence to make this happen.
This is the callback registration API, you need to call this API with the appropriate parameters in order to configure persistent storage needs.
int snmp_register_callback(int major, int minor, SNMPCallback *new_callback, void *arg);
You will need to set major to SNMP_CALLBACK_LIBRARY, minor to SNMP_CALLBACK_STORE_DATA. arg is whatever you want.
Your callback function's prototype is: int (SNMPCallback) (int majorID, int minorID, void *serverarg, void *clientarg);
The majorID, minorID and clientarg are what you passed in the callback registration above. When the callback is called you have to essentially transfer all your state from memory to disk. You do this by generating configuration lines into a buffer. The lines are of the form token followed by token parameters.
Finally storing is done using read_config_store(type, buffer); type is the application name this can be obtained from:
netsnmp_ds_get_string(NETSNMP_DS_LIBRARY_ID, NETSNMP_DS_LIB_APPTYPE);
Now, reading back the data: This is done by registering a config handler for your token using the register_config_handler function. Your handler will be invoked and you can parse in the data using the read_config_read APIs.
FUNCTION DOCUMENTATION
char* read_config_read_data (int type, char * readfrom, void * dataptr, size_t * len)
read_config_read_data reads data of a given type from a token(s) on a configuration line.
The supported types are:
ASN_INTEGER
ASN_TIMETICKS
ASN_UNSIGNED
ASN_OCTET_STR
ASN_BIT_STR
ASN_OBJECT_ID
Parameters:
type
the asn data type to be read in.
readform
the configuration line data to be read.
dataptr
an allocated pointer expected to match the type being read (int *, u_int *, char **, oid **)
len
is the length of an asn oid or octet/bit string, not required for the asn integer, unsigned integer, and timeticks types
Returns:
the next token in the configuration line. NULL if none left or if an unknown type.
Definition at line 1650 of file read_config.c.
Referenced by netsnmp_read_data_callback().
void read_config_store (const char * type, const char * line)
read_config_store intended for use by applications to store permenant configuration information generated by sets or persistent counters.
Appends line to a file named either ENV(SNMP_PERSISTENT_FILE) or '<PERSISTENT_DIRECTORY>/<type>.conf'. Adds a trailing newline to the stored file if necessary.
Parameters:
type
is the application name
line
is the configuration line written to the application name's configuration file
Returns:
void
Definition at line 1124 of file read_config.c.
References snmp_log().
Referenced by netsnmp_oid_stash_store(), and netsnmp_save_all_data().
char* read_config_store_data (int type, char * storeto, void * dataptr, size_t * len)
read_config_store_data stores data of a given type to a configuration line into the storeto buffer.
Calls read_config_store_data_prefix with the prefix parameter set to a char space. The supported types are:
ASN_INTEGER
ASN_TIMETICKS
ASN_UNSIGNED
ASN_OCTET_STR
ASN_BIT_STR
ASN_OBJECT_ID
Parameters:
type
the asn data type to be stored
storeto
a pre-allocated char buffer which will contain the data to be stored
dataptr
contains the value to be stored, the supported pointers: (int *, u_int *, char **, oid **)
len
is the length of the pre-allocated storeto buffer, not required for the asn integer, unsigned integer, and timeticks types.
Returns:
character pointer to the end of the line. NULL if an unknown type.
Definition at line 1777 of file read_config.c.
struct config_line* register_config_handler (const char * type_param, const char * token, void(* parser)(const char *, char *), void(* releaser)(void), const char * help)
register_config_handler registers handlers for certain tokens specified in certain types of files.
Allows a module writer use/register multiple configuration files based off of the type parameter. A module writer may want to set up multiple configuration files to separate out related tasks/variables or just for management of where to put tokens as the module or modules get more complex in regard to handling token registrations.
Parameters:
type
the configuration file used, e.g., if snmp.conf is the file where the token is located use 'snmp' here. If NULL the configuration file used will be snmpd.conf.
token
the token being parsed from the file. Must be non-NULL.
parser
the handler function pointer that use the specified token and the rest of the line to do whatever is required Should be non-NULL in order to make use of this API.
releaser
if non-NULL, the function specified is called if and when the configuration files are re-read. This function should free any resources allocated by the token handler function.
help
if non-NULL, used to display help information on the expected arguments after the token.
Returns:
Pointer to a new config line entry or NULL on error.
Definition at line 196 of file read_config.c.
Referenced by netsnmp_register_save_list().
void unregister_config_handler (const char * type_param, const char * token)
uregister_config_handler un-registers handlers given a specific type_param and token.
Parameters:
type_param
the configuration file used where the token is located. Used to lookup the config file entry
token
the token that is being unregistered
Returns:
void
Definition at line 283 of file read_config.c.
References SNMP_FREE.