.TH "mfd_pdu_context_s" 3 "17 Feb 2004" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mfd_pdu_context_s \- data structure for lower handler use 
.SH SYNOPSIS
.br
.PP
\fC#include <table_mfd.h>\fP
.PP
.SH "DETAILED DESCRIPTION"
.PP 
data structure for lower handler use
.PP
Definition at line 83 of file table_mfd.h.

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
