.TH "Container_iterator" 3 "28 Oct 2003" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Container_iterator \- 
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef netsnmp_ref_void * \fBloop_ctx\fP"
.br
.ti -1c
.RI "typedef netsnmp_ref_void netsnmp_ref_void * \fBkey\fP"
.br
.ti -1c
.RI "typedef netsnmp_ref_void netsnmp_ref_void * \fBdata\fP"
.br
.ti -1c
.RI "typedef netsnmp_ref_void netsnmp_ref_void * \fBdup_ctx\fP"
.br
.ti -1c
.RI "typedef netsnmp_ref_void netsnmp_ref_void int \fBreuse\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "typedef \fBint\fP (Netsnmp_Iterator_Loop_Key)(void *iterator_ctx"
.br
.RI "\fIfwd decl.\fP"
.ti -1c
.RI "void \fBnetsnmp_container_iterator_init\fP (void)"
.br
.ti -1c
.RI "netsnmp_container * \fBnetsnmp_container_iterator_get\fP (void *iterator_user_ctx, netsnmp_container_compare *compare, Netsnmp_Iterator_Loop_Key *get_first, Netsnmp_Iterator_Loop_Key *get_next, Netsnmp_Iterator_Loop_Data *get_data, Netsnmp_Iterator_Ctx_Dup *save_pos, Netsnmp_Iterator_Ctx *init_loop_ctx, Netsnmp_Iterator_Ctx *cleanup_loop_ctx, Netsnmp_Iterator_Data *free_user_ctx, int sorted)"
.br
.ti -1c
.RI "void \fBnetsnmp_container_iterator_set_data_cb\fP (netsnmp_container *c, Netsnmp_Iterator_Data *insert_data, Netsnmp_Iterator_Data *remove_data, Netsnmp_Iterator_Op *get_size)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "typedef \fBint\fP"
.br
.in -1c
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "typedef int (Netsnmp_MFD_Organize_Op)"
.PP
fwd decl.
.PP

