.TH "netsnmp_data_list_s" 3 "11 Sep 2007" "Version 5.3.2.pre1" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netsnmp_data_list_s \- used to iterate through lists of data  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <data_list.h>\fP
.PP
.SH "Detailed Description"
.PP 
used to iterate through lists of data 

.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
