.TH "snmp_alarm" 3 "27 Jul 2007" "Version 5.4.1" "net-snmp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
snmp_alarm \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "timeval \fBt\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.ti -1c
.RI "unsigned int \fBclientreg\fP"
.br
.ti -1c
.RI "timeval \fBt_last\fP"
.br
.ti -1c
.RI "timeval \fBt_next\fP"
.br
.ti -1c
.RI "void * \fBclientarg\fP"
.br
.ti -1c
.RI "SNMPAlarmCallback * \fBthecallback\fP"
.br
.ti -1c
.RI "\fBsnmp_alarm\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file snmp_alarm.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for net-snmp from the source code.
