#!/bin/sh

srcdir=`dirname $0`
srcdir=`dirname $srcdir`
srcdir=`cd $srcdir; pwd`

# set up MIBDIRS to refer to the src directory
if [ "x$MIBDIRS" = "x" ]; then
    MIBDIRS=${srcdir}/mibs
    export MIBDIRS
fi

for i in ${srcdir}/testing/fulltests/default/T* ; do
    echo "RUNNING $i"
    ${srcdir}/testing/fulltests/support/simple_run $i
done
