#!/bin/sh

QUOTEFILES="version.h bug-report"
SEDFILES="sedscript.in"
COLONFILES="README FAQ"

DOIT=

if [ $2 = "reverse" -o $2 = "tag" -o $2 = "tar" ];
then
    VERSION="$1"
    VERSIONTAG=`echo Ext-$1 | sed 's/\./-/g;'`
else
    case "$1" in
    Ext*) ;;
    *) exit 0 ;;
    esac

    VERSIONTAG="$1"
    VERSION=`echo $1 | sed 's/Ext-*//g;s/-/./g;'`
fi

if [ $2 = "add" -o $2 = "reverse" ]; then
  $DOIT perl -p -i.bak -e 's/VersionInfo="(.*)"/VersionInfo="'$VERSION'"/;' $QUOTEFILES
  $DOIT perl -p -i.bak -e 's/Version: [\.0-9a-zA-Z]+/Version: $VERSION/;' $COLONFILES
  $DOIT perl -p -i.bak -e 's#^s/VERSIONINFO/.*#s/VERSIONINFO/'$VERSION'/g#;' $SEDFILES
  $DOIT cvs commit -m "- ($QUOTEFILES $SEDFILES): version tag ( $VERSION )" $QUOTEFILES $SEDFILES $COLONFILES
fi

if [ $2 = "tag" ]; then
    $DOIT cvs tag $VERSIONTAG
fi

if [ $2 = "tar" ]; then
    $DOIT cvs -d :gserver:hardaker@dcas08.ucdavis.edu:/opt/ucd-snmp export -d ucd-snmp-$VERSION -r $VERSIONTAG ucd-snmp
    $DOIT ucd-snmp-$VERSION/remove-files ucd-snmp-$VERSION
    $DOIT tar czf ucd-snmp-$VERSION.tar.gz ucd-snmp-$VERSION
fi

exit 0
