#!/bin/sh

. ../support/simple_eval_tools.sh

TRAPHANDLE_LOGFILE=${SNMP_TMPDIR}/traphandle.log

# "inline" trap handler
echo "here: $1 $2" >> /tmp/runit
if [ "x$2" = "xtraphandle" ]; then
  cat - >>$TRAPHANDLE_LOGFILE
  exit 0
fi

HEADER snmptrapd traphandle: launching external shell script

SKIPIF NETSNMP_DISABLE_SNMPV2C
SKIPIFNOT USING_UTILITIES_EXECUTE_MODULE

#
# Begin test
#

snmp_version=v2c
TESTCOMMUNITY=testcommunity

# Make the paths of arguments $0 and $1 absolute.
NETSNMPDIR="`pwd`"
NETSNMPDIR="`dirname ${NETSNMPDIR}`"
NETSNMPDIR="`dirname ${NETSNMPDIR}`"
if [ "`echo $0|cut -c1`" = "/" ]; then
  traphandle_program="$0"
else
  traphandle_program="${NETSNMPDIR}/$0"
fi
if [ "`echo $1|cut -c1`" = "/" ]; then
  traphandle_arg="$1"
else
  traphandle_arg="${NETSNMPDIR}/$1"
fi

CONFIGTRAPD [snmp] persistentDir $SNMP_TMP_PERSISTENTDIR
CONFIGTRAPD [snmp] tempFilePattern /tmp/snmpd-tmp-XXXXXX
CONFIGTRAPD authcommunity execute $TESTCOMMUNITY
CONFIGTRAPD doNotLogTraps true
CONFIGTRAPD traphandle default "$traphandle_program" "$traphandle_arg" traphandle
CONFIGTRAPD agentxsocket /dev/null

STARTTRAPD

## 1) test notification handler

CAPTURE "snmptrap -d -Ci -t $SNMP_SLEEP -$snmp_version -c $TESTCOMMUNITY $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPTRAPD_PORT 0 .1.3.6.1.6.3.1.1.5.1 .1.3.6.1.2.1.1.4.0 s handled_inform_$snmp_version"
DELAY
CHECKORDIE "handled_inform_$snmp_version" $TRAPHANDLE_LOGFILE 

## 2) persistency: reconfigure (SIGHUP), re-test

HUPTRAPD
CAPTURE "snmptrap -d -Ci -t $SNMP_SLEEP -$snmp_version -c $TESTCOMMUNITY $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPTRAPD_PORT 0 .1.3.6.1.6.3.1.1.5.1 .1.3.6.1.2.1.1.4.0 s handled_inform2_$snmp_version"
DELAY
CHECKORDIE "handled_inform2_$snmp_version" $TRAPHANDLE_LOGFILE

## stop
STOPTRAPD

FINISHED
