#!/bin/sh

# tests common to tls and dtls usages

STARTAGENT

CAPTURE "snmpget -l ap -u bogus --defSecurityModel=tsm -On $SNMP_FLAGS $NOAUTHTESTARGS $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.3.0"

CHECK       ".1.3.6.1.2.1.1.3.0 = Timeticks:"

CAPTURE "snmpget -l ap -u bogus -T my_fingerprint=$OTHERUSERFP --defSecurityModel=tsm -On $SNMP_FLAGS $NOAUTHTESTARGS $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.4.0"

CHECK              ".1.3.6.1.2.1.1.4.0 = "
CHECKAGENTCOUNT 2  "otheruser"

CAPTURE "snmpget -l ap -u bogus -T my_fingerprint=$INVALIDUSERFP --defSecurityModel=tsm -On $SNMP_FLAGS $NOAUTHTESTARGS $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.3.0"

CHECK "authorizationError"

STOPAGENT

FINISHED

