#!/bin/sh

export NET_SNMP_CRT_CFGTOOL="${builddir}/net-snmp-config"
NSCERT="perl $SNMP_BASEDIR/../../../local/net-snmp-cert"
NSCERTARGS="-C $SNMP_TMPDIR"

# produce the certificates to use

# snmpd
CAPTURE $NSCERT gencert -t snmpd   --cn `hostname` $NSCERTARGS
SERVERFP=`$NSCERT showcerts --fingerprint --brief snmpd  $NSCERTARGS`
CHECKVALUEISNT "$SERVERFP" "" "generated fingerprint for snmpd certificate"

# user
CAPTURE $NSCERT gencert -t snmpapp --cn 'testuser'  $NSCERTARGS
TESTUSERFP=`$NSCERT showcerts --fingerprint --brief snmpapp $NSCERTARGS`
CHECKVALUEISNT "$TESTUSERFP" "" "generated fingerprint for testuser certificate"

# user 1.5
CAPTURE $NSCERT gencert -t snmpapp2 --cn 'testuser2'  $NSCERTARGS
TESTUSER2FP=`$NSCERT showcerts --fingerprint --brief snmpapp2 $NSCERTARGS`
CHECKVALUEISNT "$TESTUSER2FP" "" "generated fingerprint for testuser certificate"

# user 2
CAPTURE $NSCERT gencert -t otheruser --cn 'otheruser'  $NSCERTARGS
OTHERUSERFP=`$NSCERT showcerts --fingerprint --brief otheruser $NSCERTARGS`
CHECKVALUEISNT "$OTHERUSERFP" "" "generated fingerprint for otheruser certificate"

# user 3
CAPTURE $NSCERT gencert -t invaliduser --cn 'invaliduser'  $NSCERTARGS
INVALIDUSERFP=`$NSCERT showcerts --fingerprint --brief invaliduser $NSCERTARGS`
CHECKVALUEISNT "$INVALIDUSERFP" "" "generated fingerprint for otheruser certificate"

# user 4
CAPTURE $NSCERT gencert -t unmapped --cn 'unmapped'  $NSCERTARGS
UNMAPPEDFP=`$NSCERT showcerts --fingerprint --brief unmapped $NSCERTARGS`
CHECKVALUEISNT "$UNMAPPEDFP" "" "generated fingerprint for unmapped certificate"

# user 5
CAPTURE $NSCERT gencert -t mappeduser --cn 'mappeduser'  $NSCERTARGS
MAPPEDUSERFP=`$NSCERT showcerts --fingerprint --brief mappeduser $NSCERTARGS`
CHECKVALUEISNT "$MAPPEDUSERFP" "" "generated fingerprint for mappeduser certificate"

# user 6: SAN email
CAPTURE $NSCERT gencert -t email --san email:foobaruser@example.com  $NSCERTARGS
EMAILUSERFP=`$NSCERT showcerts --fingerprint --brief email $NSCERTARGS`
CHECKVALUEISNT "$EMAILUSERFP" "" "generated fingerprint for email certificate"

# user 7: SAN dns
CAPTURE $NSCERT gencert -t dns --san DNS:foobar.example.com  $NSCERTARGS
DNSUSERFP=`$NSCERT showcerts --fingerprint --brief dns $NSCERTARGS`
CHECKVALUEISNT "$DNSUSERFP" "" "generated fingerprint for dns certificate"

# user 8: SAN IPv4
CAPTURE $NSCERT gencert -t ipaddr --san IP:127.0.0.1  $NSCERTARGS
IPUSERFP=`$NSCERT showcerts --fingerprint --brief ipaddr $NSCERTARGS`
CHECKVALUEISNT "$IPUSERFP" "" "generated fingerprint for ipaddr certificate"


# CA certificate

# temp fixes:
touch $SNMP_TMPDIR/tls/.index
echo "01" > $SNMP_TMPDIR/tls/.serial

CAPTURE $NSCERT genca --cn ca-net-snmp.org  $NSCERTARGS
CAFP=`$NSCERT showcas --fingerprint --brief ca-net-snmp.org $NSCERTARGS`
CHECKVALUEISNT "$CAFP" "" "generated fingerprint for ca-net-snmp.org certificate"

# user 9: CA signed cert
CAPTURE $NSCERT gencert -t causer --with-ca ca-net-snmp.org --san email:user8@test.net-snmp.org  $NSCERTARGS
CAUSERFP=`$NSCERT showcerts --fingerprint --brief causer $NSCERTARGS`
CHECKVALUEISNT "$CAUSERFP" "" "generated fingerprint for causer certificate"

CONFIGAGENT '[snmp]' debugTokens tsm
CONFIGAGENT '[snmp]' doDebugging 1
CONFIGAGENT '[snmp]' defX509ServerPub $SERVERFP

# common name mappings
CONFIGAGENT certSecName 9  $TESTUSERFP     --cn
CONFIGAGENT certSecName 10 $TESTUSER2FP    --cn
CONFIGAGENT certSecName 11 $OTHERUSERFP    --cn
CONFIGAGENT certSecName 12 $INVALIDUSERFP  --cn

CONFIGAGENT certSecName 20 $MAPPEDUSERFP --sn aftermapping
CONFIGAGENT certSecName 21 $EMAILUSERFP  --rfc822
CONFIGAGENT certSecName 22 $DNSUSERFP    --dns
CONFIGAGENT certSecName 23 $IPUSERFP     --ip

CONFIGAGENT certSecName 100 $CAFP        --rfc822

# *** INTENTIONALLY NOT MAPPING AT ALL: ***
# CONFIGAGENT certSecName 1000 $UNMAPPEDFP ....

CONFIGAPP   defX509ServerPub  	  $SERVERFP
CONFIGAPP   defSecurityModel      tsm

CONFIGAGENT  rwuser -s tsm testuser authpriv
CONFIGAGENT  rwuser -s tsm testuser2 authpriv
CONFIGAGENT  rwuser -s tsm otheruser authpriv
CONFIGAGENT  rwuser -s tsm aftermapping authpriv

CONFIGAGENT  rwuser -s tsm foobaruser@example.com authpriv
CONFIGAGENT  rwuser -s tsm foobar.example.com authpriv
CONFIGAGENT  rwuser -s tsm 127.0.0.1 authpriv
CONFIGAGENT  rwuser -s tsm user8@test.net-snmp.org authpriv
