#!/bin/sh

. ../support/olducd_eval_tools.sh

HEADER DTLS-UDP Transport

SKIPIFNOT NETSNMP_TRANSPORT_DTLSUDP_DOMAIN

#
# Begin test
#

# Setup the tls infrastructure
. ./Stls

SNMP_TRANSPORT_SPEC=tlstcp
export SNMP_TRANSPORT_SPEC
export SNMP_SNMPD_PORT
export SNMP_TEST_DEST

. ./Stlstests
