/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 5.0 2002/04/20 07:30:13 hardaker Exp $
 */
#ifndef NSTAGENTMODULEOBJECT_H
#define NSTAGENTMODULEOBJECT_H

/*
 * function declarations 
 */
void            init_nstAgentModuleObject(void);

#endif                          /* NSTAGENTMODULEOBJECT_H */
