#!/bin/sh

# build the C-test file head
cat > $2.c << EOF1

/* net-snmp standard headers */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>

/* testing specific header */
#include <net-snmp/library/testing.h>

/* standard headers */
#include <stdio.h>
#include <sys/types.h>
#ifdef HAVE_STDLIB_H
#include <stdlib.h>
#endif
#if HAVE_STRING_H
#include <string.h>
#else
#include <strings.h>
#endif

int
main(int argc, char *argv) {

EOF1

# add in the actual library tests
cat $1 >> $2.c

# build the C-test file tail
cat >> $2.c << EOF2

   if (__did_plan == 0) {
       PLAN(__test_counter);
   }

   return(0);
}

EOF2

# now compile the whole mess
${builddir}/libtool --mode=link `${builddir}/net-snmp-config --build-command` -I$builddir/include -I$srcdir/include -o $2.lt $2.c ${builddir}/snmplib/libnetsnmp.la `${builddir}/net-snmp-config --external-libs`
echo $2.lt;
