#!/usr/bin/env perl
#
# Obtain a local IP address that differs from the localhost IP address. Tests
# like T180 to T185 verify the clientaddr configuration directive. These tests
# make snmpd to send its outgoing traps from the localhost address to the
# address returned by this script. These tests can only verify the effect of the
# "clientaddr" configuration directive if this script returns another address
# than the localhost address.

use strict;
use warnings;

# For older Perl versions AF_INET6 is defined in the Socket6 package. For newer
# Perl versions all IPv6 functionality we need is defined in the Socket package.
BEGIN {
    # Try to load Socket6
    if (eval "require Socket6; Socket6->import(qw(AF_INET6 inet_ntop inet_pton pack_sockaddr_in6 sockaddr_in6)); 1") {
        # If loading Socket6 succeeded, only load the v4 parts from Socket.
        require Socket;
        Socket->import(qw(AF_INET SOCK_DGRAM pack_sockaddr_in sockaddr_in));
    } else {
        # If loading Socket6 failed, assume a modern Perl where Socket has
	# everything.
        require Socket;
        Socket->import(qw(AF_INET AF_INET6 SOCK_DGRAM inet_ntop inet_pton
                          pack_sockaddr_in pack_sockaddr_in6 sockaddr_in sockaddr_in6));
    }
}


my $v6 = defined($ARGV[0]) && $ARGV[0] eq "ipv6";
my ($af, $dest, $noaddr);
if ($v6) {
    $af = AF_INET6;
    # dns.google
    $dest = '2001:4860:4860::8888';
    $noaddr = '::';
} else {
    $af = AF_INET;
    # dns.google
    $dest = '8.8.8.8';
    $noaddr = '0.0.0.0';
}
socket(my $sock, $af, SOCK_DGRAM, 0) or die "socket creation failed: $!";
my $myip;
if ($v6) {
    connect($sock, pack_sockaddr_in6(53, inet_pton($af, $dest)));
    my ($port, $ip6_address) = sockaddr_in6(getsockname($sock));
    $myip = inet_ntop($af, $ip6_address);
    exit 1 if $myip eq $noaddr;
} else {
    connect($sock, pack_sockaddr_in(53, inet_pton($af, $dest)));
    my ($port, $myaddr) = sockaddr_in(getsockname($sock));
    $myip = inet_ntop($af, $myaddr);
    exit 1 if $myip eq $noaddr;
}
print $myip, "\n";
exit 0;
