#!/usr/bin/perl

use Getopt::Long;
use strict;

my %opts = ('g' => 'default',
	    'd' => 'fulltests');
GetOptions(\%opts, 
	   "v",
	   "h",
	   "q",
	   "g=s",
	   "debug") || usage();
usage() if ($opts{'h'});

my %args = (
	    verbosity => ($opts{'v'} ? 1 : 0),
	    exec => \&decide_exec,
	    failures => ($opts{'q'} ? 0 : 1),
	    errors => ($opts{'q'} ? 0 : 1),
	   );

# create the testing harness infrastructure
use TAP::Harness;
my $harness = TAP::Harness->new(\%args);

# gather the tests
my @tests = gather_tests($opts{'g'});

# run the actual tests
DEBUG("Running tests:\n"); 
DEBUG("-" x 78, "\n");
$harness->runtests(@tests);

########################################
# decides how we should execute a test
#
sub decide_exec {
    my ( $harness, $test_file ) = @_;
    if ($test_file =~ /c$/) {
	return [$test_file];
    }
    return undef;
}

sub gather_tests {
    my ( $groups ) = @_;
    my @groups;

    # figure out the list of groups we need to search through
    if ($groups eq 'all') {
	# find every group we can
	# we exclude:
	#  - things not a directory
	#  - anything with "template" in the name
	@groups =
	  grep { !/(template|support)/ &&
		   -d $_ && s/$opts{'d'}.// } glob("$opts{'d'}/*");
    } else {
	# they specified a comma separated list
	@groups = split(/,\s*/, $groups);
    }
    DEBUG("Checking groups: ", join(", ", @groups), "\n");

    my @tests;
    foreach my $group (@groups) {
	my @files;

	DEBUG("checking group $group\n");

	if (! -d "$opts{'d'}/$group") {
	    ERROR("group '$group' is not a directory under '$opts{'d'}'; ignoring\n");
	    next;
	}

	# push on all files that start with T[NUM]*
	push_or_skip(\@tests, glob("$opts{'d'}/$group/T[0-9]*"));
    }

    return @tests;
}

sub push_or_skip {
    my ($array, @files) = @_;
    foreach my $file (@files) {
	next if ($file =~ /.(bak|old|orig|rej)$/);
	next if ($file =~ /~$/);
	DEBUG("  Adding file $file\n");
	my $title = "$file";
	$title =~ s/$opts{'d'}.//;
	push @$array, [$file, $title];
    }
}

sub build_test {
    my ($testfile) = @_;
}

# usage output
sub usage {
    print "$0 [-v] [-q] [-g GROUP]\n";
    print "  -v\t\tRuns in verbose mode; dumping all test output\n";
    print "  -q\t\tRuns in quieter mode; dumps less test output\n";
    print "  -g GROUP\tRuns the group of specified tests (default = 'default')\n";
    print "\t\t(use 'all' to run all tests)\n";
    print "  -h\t\tThis help output\n";
    print "  --debug\t\tDebugging output\n";
    exit;
}

sub DEBUG {
    return if (!$opts{'debug'});
    print @_;
}

sub ERROR {
    print STDERR "Error:", @_;
}
