/* This file is automatically generated by configure.  Do not modify by hand. */
  if (should_init("proxy")) shutdown_proxy();
 
#ifdef USING_UCD_SNMP_MODULE
  if (should_init("pass_persist")) shutdown_pass_persist();
#endif
