#!/bin/sh

. ../support/simple_eval_tools.sh

HEADER DTLS-UDP server certificate tests

SKIPIFNOT NETSNMP_TRANSPORT_TLSTCP_DOMAIN

#
# Begin test
#

SNMP_TRANSPORT_SPEC=dtlsudp
export SNMP_TRANSPORT_SPEC
export SNMP_SNMPD_PORT
export SNMP_TEST_DEST

. ./Stlsservertests
