#!/bin/sh

export NET_SNMP_CRT_CFGTOOL="${builddir}/net-snmp-config"
NSCERT="perl $SNMP_BASEDIR/../../../local/net-snmp-cert"
NSCERTARGS="-C $SNMP_TMPDIR"

DOSETTEST() {
  value=$1
  args=$2

  CAPTURE "snmpset $args .1.3.6.1.2.1.1.6.0 s '$value'"

  CAPTURE "snmpget $args .1.3.6.1.2.1.1.6.0"

  CHECK "$value"
}


DOFAILSETTEST() {
  value=$1
  args=$2

  CAPTURE "snmpset $args .1.3.6.1.2.1.1.6.0 s '$value'"

  CAPTURE "snmpget $args .1.3.6.1.2.1.1.6.0"

  CHECKCOUNT 0 "$value"
}
