#!/bin/sh

SNMP_TEST_TIMEOUT=180

. ../support/simple_eval_tools.sh

HEADER TLS-TCP user certificate tests

SKIPIFNOT NETSNMP_TRANSPORT_TLSTCP_DOMAIN

#
# Begin test
#

SNMP_TRANSPORT_SPEC=tlstcp

. ./STlsUsers
