#!/bin/sh

. ../support/simple_eval_tools.sh

HEADER DTLS-UDP trap tests

SKIPIFNOT NETSNMP_TRANSPORT_DTLSUDP_DOMAIN

#
# Begin test
#

SNMP_TRANSPORT_SPEC=dtlsudp
export SNMP_TRANSPORT_SPEC
export SNMP_SNMPTRAPD_PORT
export SNMP_TEST_DEST

. ./Stlstrapdusertests
