#!/bin/sh

set -eux
if killall snmpd; then :; fi
export LD_LIBRARY_PATH="$PWD/snmplib/.libs:$PWD/agent/.libs:$PWD/agent/helpers/.libs:"
export MIBDIRS="$PWD/mibs"
export SNMP_PERSISTENT_DIR=/tmp/net-snmp
export SNMP_SNMPD_PORT=1161
for dir in "$PWD"/python/build/lib.*; do
    export PYTHONPATH="${dir}"
    break
done
mkdir -p "$SNMP_PERSISTENT_DIR"
agent/snmpd -I-smux -r -f -Lo -c python/netsnmp/tests/snmpd.conf localhost:${SNMP_SNMPD_PORT} &
pid=$!
PYTHONPROG=$(sed -n 's/^S\["PYTHONPROG"\]="\(.*\)"$/\1/p' config.status)
[ -n "$PYTHONPROG" ]
$PYTHONPROG -m unittest python/netsnmp/tests/test.py
kill $pid
wait
