/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef SNMPTLSTMPARAMSTABLE_H
#define SNMPTLSTMPARAMSTABLE_H

/*
 * function declarations 
 */
void            init_snmpTlstmParamsTable(void);

/*
 * column number definitions for table snmpTlstmParamsTable 
 */
#define COLUMN_SNMPTLSTMPARAMSCLIENTFINGERPRINT		1
#define COLUMN_SNMPTLSTMPARAMSSTORAGETYPE		2
#define COLUMN_SNMPTLSTMPARAMSROWSTATUS		3
#endif                          /* SNMPTLSTMPARAMSTABLE_H */
