#
# Minimum environment and virtual path setup
#
SHELL		= /bin/sh
srcdir		= @srcdir@
top_srcdir	= @top_srcdir@
VPATH		= @srcdir@
@SET_MAKE@

#
# Paths
#
prefix		= @prefix@
exec_prefix	= @exec_prefix@
bindir		= @bindir@
sbindir		= @sbindir@
libdir		= @libdir@
datadir		= @datadir@
includedir	= @includedir@/ucd-snmp
mandir		= @mandir@
man1dir		= $(mandir)/man1
man3dir		= $(mandir)/man3
man5dir		= $(mandir)/man5
man8dir		= $(mandir)/man8
snmplibdir	= $(datadir)/snmp
mibdir		= $(snmplibdir)/mibs
persistentdir	= @PERSISTENT_DIRECTORY@


#
# Programs
#
INSTALL		= @INSTALL@
SED		= @SED@
RANLIB		= @RANLIB@
LN_S		= @LN_S@

#
# Compiler arguments
#
CFLAGS		= @CFLAGS@
EXTRACPPFLAGS	= @EXTRACPPFLAGS@
LDFLAGS		= @LDFLAGS@ 

#
# Shared library commands (or not)
#
SHLIB_CFLAGS		= @SHLIB_CFLAGS@
SHLIB_EXTENSION		= @SHLIB_EXTENSION@
SHLIB_VERSION		= @SHLIB_VERSION@
SHLIB_LDCONFIG_CMD	= @SHLIB_LDCONFIG_CMD@
SHLIB_LD_CMD		= @SHLIB_LD_CMD@
SHLIB_LD_LIBS		= @SHLIB_LD_LIBS@
CC_RUNTIME_ARG		= @CC_RUNTIME_ARG@

