#
# Minimum environment and virtual path setup
#
SHELL		= /bin/sh
srcdir		= @srcdir@
top_srcdir	= @top_srcdir@
VPATH		= @srcdir@
VERSION		= @VERSION@
@SET_MAKE@

#
# Paths
#
prefix		= @prefix@
exec_prefix	= @exec_prefix@
bindir		= @bindir@
sbindir		= @sbindir@
libdir		= @libdir@
datadir		= @datadir@
includedir	= @includedir@/ucd-snmp
mandir		= @mandir@
man1dir		= $(mandir)/man1
man3dir		= $(mandir)/man3
man5dir		= $(mandir)/man5
man8dir		= $(mandir)/man8
snmplibdir	= $(datadir)/snmp
mibdir		= $(snmplibdir)/mibs
persistentdir	= @PERSISTENT_DIRECTORY@


#
# Programs
#
INSTALL		= $(LIBTOOL) --mode=install @INSTALL@
SED		= @SED@
LN_S		= @LN_S@
#AUTOCONF	= @AUTOCONF@
#AUTOHEADER	= @AUTOHEADER@
AUTOCONF	= autoconf
AUTOHEADER	= autoheader

#
# Compiler arguments
#
CFLAGS		= @CFLAGS@
EXTRACPPFLAGS	= @EXTRACPPFLAGS@
LDFLAGS		= @LDFLAGS@ 
LIBTOOL		= @LIBTOOL@ @LIBTOOLFLAGS@
EXEEXT		= @EXEEXT@
SHVFLAGS	= @SHVFLAGS@

# Misc Compiling Stuff
CC	        = @CC@
# version number is prefixed by a 0 for a better shared library version number
LIB_LD_CMD      = $(LIBTOOL) --mode=link $(CC) $(CFLAGS) -rpath $(libdir) $(SHVFLAGS) -o
LIB_EXTENSION   = la
LIB_VERSION     =
LIB_LDCONFIG_CMD = $(LIBTOOL) --mode=finish $(libdir)
LINK		= $(LIBTOOL) --mode=link $(CC)
# RANLIB 	= @RANLIB@
RANLIB		= :

# libtool definitions
.SUFFIXES: .c .o .lo
.c.lo:
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<
