#!/bin/sh

# this shell script is designed to merely dump the configuration
# information about how the net-snmp package was compiled.  The
# information is particularily useful for applications that need to
# link against the net-snmp libraries and hence must know about any
# other libraries that must be linked in as well.

if test "x$1" = "x"; then
  usage="yes"
else
  case $1 in
    --cflags)
      echo -I/usr/include/rpm -g -I/home/hardaker/src/smip/iptables/include -Wall -Wstrict-prototypes -Wwrite-strings -Wcast-qual -Wno-char-subscripts -Dlinux
      ;;
    --agent-libs)
      # should be different some day
      echo -ldl -ldb1 -lz -lpopt -lcrypto -lm -L/home/hardaker/src/smip/iptables/libiptc -liptc
      ;;
    --libs)
      echo -lcrypto -lm -L/home/hardaker/src/smip/iptables/libiptc -liptc
      ;;
    --version)
      echo 5.0.not-even-close
      ;;
    --help)
      usage="yes"
      ;;
    --prefix)
      echo /usr/local
      ;;
    --exec-prefix)
      echo @exec-prefix@
      ;;
    *)
      echo "unknown option $1"
      usage="yes"
      ;;
  esac
fi

if test "x$usage" = "xyes"; then
  echo ""
  echo "Usage:"
  echo "  net-snmp-config [--cflags] [--agent-libs] [--libs] [--version]"
  echo ""
  echo "You can then compile agent subagents using something like:"
  echo '  cc -o mysubagent mysubagent.c `net-snmp-config --agent-libs`'
  echo ""
fi  
