#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv1 getnext of system.sysUpTime

#
# Begin test
#

# standard V1 configuration: testcomunnity
. ./Sv1config

STARTAGENT

CAPTURE "snmpgetnext -On $SNMP_FLAGS -c testcommunity -v 1 udp:localhost:$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.3"

STOPAGENT

CHECK ".1.3.6.1.2.1.1.3.0 = Timeticks:"

FINISHED
