#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv2c get of system.sysUpTime.0

#
# Begin test
#

# standard V2C configuration: testcomunnity
. ./Sv2cconfig

STARTAGENT

CAPTURE "snmpget -On $SNMP_FLAGS -v 2c udp:localhost:$SNMP_SNMPD_PORT testcommunity .1.3.6.1.2.1.1.3.0"

STOPAGENT

CHECK ".1.3.6.1.2.1.1.3.0 = Timeticks:"

FINISHED
