#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv3 getnext using initial of system.sysUpTime.0

#
# Begin test
#

# standard V3 configuration for initial user
. ./Sv3config

STARTAGENT

CAPTURE "snmpgetnext $SNMP_FLAGS -v 3 -l nanp -u initial -n xxx localhost system.sysUpTime"

STOPAGENT

CHECK "system.sysUpTime.0 = Timeticks:"

FINISHED
