#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv3 informs received and sent by tools

#
# Begin test
#

CONFIGTRAPD createUser testuser MD5 TESTPASSPHRASE

STARTTRAPD

CAPTURE "snmptrap -Ci -d $SNMP_SNMPTRAPD_PORT -v 3 -u testuser -a MD5 -A TESTPASSPHRASE -l anp localhost 0 .1.3.6.1.6.3.1.1.5.1 system.sysContact.0 s blah"

STOPTRAPD

CHECKTRAPD "coldStart"

FINISHED
