#!/bin/sh

. ../eval_tools.sh

HEADER root partition on Solaris using HOST-RESOURCES

if test `uname -s` != "SunOS" ; then
    # a bogus skip for !suns
    SKIPIFNOT XXXYYYZZZ
fi

SKIPIFNOT USING_HOST_MODULE

#
# Begin test
#

# standard V1 configuration: testcomunnity
. ./Sv1config

STARTAGENT

# ask for the description of the first CPU in the system

CAPTURE "snmpget -On $SNMP_FLAGS -c testcommunity -v 1 udp:localhost:$SNMP_SNMPD_PORT .1.3.6.1.2.1.25.2.3.1.3.4"

STOPAGENT

CHECKORDIE "^.1.3.6.1.2.1.25.2.3.1.3.4 = STRING: /$"

FINISHED
