#!/bin/sh

. ../eval_tools.sh

HEADER initial load device on Solaris using HOST-RESOURCES

if test `uname -s` != "SunOS" ; then
    # a bogus skip for !suns
    SKIPIFNOT XXXYYYZZZ
fi

SKIPIFNOT USING_HOST_MODULE

SKIPIF DISABLE_SNMPV2C

#
# Begin test
#

# standard V1 configuration: testcomunnity
. ./Sv1config

STARTAGENT

# ask  the index of the initial device

CAPTURE "snmpget -On $SNMP_FLAGS -c testcommunity -v 1 $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPD_PORT .1.3.6.1.2.1.25.1.3.0"

STOPAGENT

CHECKORDIE "^.1.3.6.1.2.1.25.1.3.0 = INTEGER:"

FINISHED
