#!/bin/sh

. ../eval_tools.sh

HEADER TCP Transport

SKIPIFNOT USING_MIBII_SYSTEM_MIB_MODULE
SKIPIFNOT NETSNMP_TRANSPORT_TCP_DOMAIN

#
# Begin test
#

# configure the agent to accept user initial with noAuthNoPriv
. ./Sv3config

SNMP_TRANSPORT_SPEC=tcp

. ./Stransport
