#!/bin/sh

. ../eval_tools.sh

HEADER UDP6 Transport

SKIPIFNOT USING_MIBII_SYSTEM_MIB_MODULE
SKIPIFNOT NETSNMP_TRANSPORT_UDPIPV6_DOMAIN

#
# Begin test
#

# configure the agent to accept user initial with noAuthNoPriv
. ./Sv3config

SNMP_TRANSPORT_SPEC=udp6
SNMP_TEST_DEST="[::1]:"

. ./Stransport
