#!/bin/sh

. ../eval_tools.sh

HEADER DTLS-UDP Transport

SKIPIFNOT USING_MIBII_SYSTEM_MIB_MODULE
SKIPIFNOT NETSNMP_TRANSPORT_DTLSUDP_DOMAIN

#
# Begin test
#

SNMP_TRANSPORT_SPEC=dtlsudp
export SNMP_TRANSPORT_SPEC

CONFIGAGENT '[snmp]' defX509ServerPub  	`pwd`/test-localhost.cert
CONFIGAGENT '[snmp]' defX509ServerPriv 	`pwd`/test-localhost.priv
CONFIGAGENT '[snmp]' defX509ClientCerts `pwd`/test-user.cert

CONFIGAGENT '[snmp]' defX509ClientPub  	`pwd`/test-user.cert
CONFIGAGENT '[snmp]' defX509ClientPriv 	`pwd`/test-user.priv
CONFIGAGENT '[snmp]' defX509ServerCerts `pwd`/test-localhost.cert

CONFIGAGENT '[snmp]' AllowSelfSignedX509 1

CONFIGAPP   defX509ClientPub  	`pwd`/test-user.cert
CONFIGAPP   defX509ClientPriv 	`pwd`/test-user.priv
CONFIGAPP   defX509ServerCerts  `pwd`/test-localhost.cert

CONFIGAPP   '[snmp]' defX509ServerPub  	`pwd`/test-localhost.cert
CONFIGAPP   '[snmp]' defX509ServerPriv 	`pwd`/test-localhost.priv
CONFIGAPP   '[snmp]' defX509ClientCerts `pwd`/test-user.cert

CONFIGAPP   AllowSelfSignedX509 1

export SNMP_TRANSPORT_SPEC
export SNMP_SNMPD_PORT
export SNMP_TEST_DEST

CONFIGAGENT  rwuser -s tsm dtlstestuser authpriv

STARTAGENT

CAPTURE "snmpget -l ap -u bogus --defSecurityModel=tsm -On $SNMP_FLAGS $NOAUTHTESTARGS $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.3.0"

STOPAGENT

CHECK ".1.3.6.1.2.1.1.3.0 = Timeticks:"

FINISHED

