config_require(hardware/memory/hw_mem)
config_arch_require(aix4,      hardware/memory/memory_aix)
config_arch_require(aix5,      hardware/memory/memory_aix)
config_arch_require(darwin8,   hardware/memory/memory_darwin)
config_arch_require(dynix,     hardware/memory/memory_dynix)
config_arch_require(freebsd2,  hardware/memory/memory_freebsd)
config_arch_require(freebsd3,  hardware/memory/memory_freebsd)
config_arch_require(freebsd4,  hardware/memory/memory_freebsd)
config_arch_require(freebsd5,  hardware/memory/memory_freebsd)
config_arch_require(freebsd6,  hardware/memory/memory_freebsd)
config_arch_require(hpux10,    hardware/memory/memory_hpux)
config_arch_require(hpux11,    hardware/memory/memory_hpux)
config_arch_require(irix6,     hardware/memory/memory_irix)
config_arch_require(linux,     hardware/memory/memory_linux)
config_arch_require(netbsd,    hardware/memory/memory_netbsd)
config_arch_require(netbsd1,   hardware/memory/memory_netbsd)
config_arch_require(netbsdelf, hardware/memory/memory_netbsd)
config_arch_require(netbsdelf2,hardware/memory/memory_netbsd)
config_arch_require(netbsdelf3,hardware/memory/memory_netbsd)
config_arch_require(openbsd2,  hardware/memory/memory_netbsd)
config_arch_require(openbsd3,  hardware/memory/memory_netbsd)
config_arch_require(openbsd4,  hardware/memory/memory_netbsd)
config_arch_require(solaris2,  hardware/memory/memory_solaris)
