char *find_field();
char *skip_white();
int get_ps_output();
int get_exec_output();
void setPerrorstatus();
void seterrorstatus();
void copy_word();
int clear_cache();
int update_hook();
RETSIGTYPE update_config();
struct extensible *get_exten_instance();
unsigned char *var_extensible_relocatable();
int restart_hook();
void print_mib_oid();
void sprint_mib_oid();
int parse_miboid();
void free_config();
int read_config();
int klookup();
int subtree_old_size();
void init_extensible();
int exec_command();
int shell_command();
int checkmib();
int sh_count_procs();
int fixProcError();
int fixExecError();
