# DO NOT DELETE THIS LINE -- make depend depends on it.


./header_complex.o: header_complex.c header_complex.h /usr/include/alloca.h
./header_complex.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
./header_complex.o: /usr/include/bits/byteswap.h /usr/include/bits/endian.h
./header_complex.o: /usr/include/bits/in.h /usr/include/bits/local_lim.h
./header_complex.o: /usr/include/bits/posix1_lim.h
./header_complex.o: /usr/include/bits/posix2_lim.h
./header_complex.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
./header_complex.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
./header_complex.o: /usr/include/bits/sockaddr.h /usr/include/bits/socket.h
./header_complex.o: /usr/include/bits/stdio_lim.h /usr/include/bits/time.h
./header_complex.o: /usr/include/bits/types.h /usr/include/bits/uio.h
./header_complex.o: /usr/include/bits/waitflags.h
./header_complex.o: /usr/include/bits/waitstatus.h /usr/include/bits/wchar.h
./header_complex.o: /usr/include/bits/wordsize.h /usr/include/bits/xopen_lim.h
./header_complex.o: /usr/include/endian.h /usr/include/features.h
./header_complex.o: /usr/include/_G_config.h /usr/include/gconv.h
./header_complex.o: /usr/include/gnu/stubs.h /usr/include/libio.h
./header_complex.o: /usr/include/limits.h /usr/include/linux/limits.h
./header_complex.o: /usr/include/netinet/in.h /usr/include/stdint.h
./header_complex.o: /usr/include/stdio.h /usr/include/stdlib.h
./header_complex.o: /usr/include/string.h /usr/include/sys/cdefs.h
./header_complex.o: /usr/include/syslog.h /usr/include/sys/select.h
./header_complex.o: /usr/include/sys/socket.h /usr/include/sys/syslog.h
./header_complex.o: /usr/include/sys/sysmacros.h /usr/include/sys/time.h
./header_complex.o: /usr/include/sys/types.h /usr/include/sys/uio.h
./header_complex.o: /usr/include/sys/un.h /usr/include/time.h
./header_complex.o: /usr/include/wchar.h /usr/include/xlocale.h
./header_complex.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/limits.h
./header_complex.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stdarg.h
./header_complex.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
./header_complex.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/syslimits.h
./kernel_sunos5.o: kernel_sunos5.c
./testdelayed.o: testdelayed.c testdelayed.h /usr/include/alloca.h
./testdelayed.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
./testdelayed.o: /usr/include/bits/byteswap.h /usr/include/bits/confname.h
./testdelayed.o: /usr/include/bits/endian.h /usr/include/bits/environments.h
./testdelayed.o: /usr/include/bits/in.h /usr/include/bits/local_lim.h
./testdelayed.o: /usr/include/bits/posix1_lim.h /usr/include/bits/posix2_lim.h
./testdelayed.o: /usr/include/bits/posix_opt.h
./testdelayed.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
./testdelayed.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
./testdelayed.o: /usr/include/bits/sockaddr.h /usr/include/bits/socket.h
./testdelayed.o: /usr/include/bits/stdio_lim.h /usr/include/bits/time.h
./testdelayed.o: /usr/include/bits/types.h /usr/include/bits/uio.h
./testdelayed.o: /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h
./testdelayed.o: /usr/include/bits/wchar.h /usr/include/bits/wordsize.h
./testdelayed.o: /usr/include/bits/xopen_lim.h /usr/include/endian.h
./testdelayed.o: /usr/include/features.h /usr/include/_G_config.h
./testdelayed.o: /usr/include/gconv.h /usr/include/getopt.h
./testdelayed.o: /usr/include/gnu/stubs.h /usr/include/libio.h
./testdelayed.o: /usr/include/limits.h /usr/include/linux/limits.h
./testdelayed.o: /usr/include/netinet/in.h /usr/include/stdint.h
./testdelayed.o: /usr/include/stdio.h /usr/include/stdlib.h
./testdelayed.o: /usr/include/string.h /usr/include/sys/cdefs.h
./testdelayed.o: /usr/include/syslog.h /usr/include/sys/select.h
./testdelayed.o: /usr/include/sys/socket.h /usr/include/sys/syslog.h
./testdelayed.o: /usr/include/sys/sysmacros.h /usr/include/sys/time.h
./testdelayed.o: /usr/include/sys/types.h /usr/include/sys/uio.h
./testdelayed.o: /usr/include/sys/un.h /usr/include/time.h
./testdelayed.o: /usr/include/unistd.h /usr/include/wchar.h
./testdelayed.o: /usr/include/xlocale.h
./testdelayed.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/limits.h
./testdelayed.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stdarg.h
./testdelayed.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
./testdelayed.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/syslimits.h
./testhandler.o: testhandler.c testhandler.h /usr/include/alloca.h
./testhandler.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
./testhandler.o: /usr/include/bits/byteswap.h /usr/include/bits/endian.h
./testhandler.o: /usr/include/bits/in.h /usr/include/bits/local_lim.h
./testhandler.o: /usr/include/bits/posix1_lim.h /usr/include/bits/posix2_lim.h
./testhandler.o: /usr/include/bits/pthreadtypes.h /usr/include/bits/sched.h
./testhandler.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
./testhandler.o: /usr/include/bits/sockaddr.h /usr/include/bits/socket.h
./testhandler.o: /usr/include/bits/stdio_lim.h /usr/include/bits/time.h
./testhandler.o: /usr/include/bits/types.h /usr/include/bits/uio.h
./testhandler.o: /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h
./testhandler.o: /usr/include/bits/wchar.h /usr/include/bits/wordsize.h
./testhandler.o: /usr/include/bits/xopen_lim.h /usr/include/endian.h
./testhandler.o: /usr/include/features.h /usr/include/_G_config.h
./testhandler.o: /usr/include/gconv.h /usr/include/gnu/stubs.h
./testhandler.o: /usr/include/libio.h /usr/include/limits.h
./testhandler.o: /usr/include/linux/limits.h /usr/include/netinet/in.h
./testhandler.o: /usr/include/stdint.h /usr/include/stdio.h
./testhandler.o: /usr/include/stdlib.h /usr/include/string.h
./testhandler.o: /usr/include/sys/cdefs.h /usr/include/syslog.h
./testhandler.o: /usr/include/sys/select.h /usr/include/sys/socket.h
./testhandler.o: /usr/include/sys/syslog.h /usr/include/sys/sysmacros.h
./testhandler.o: /usr/include/sys/time.h /usr/include/sys/types.h
./testhandler.o: /usr/include/sys/uio.h /usr/include/sys/un.h
./testhandler.o: /usr/include/time.h /usr/include/wchar.h
./testhandler.o: /usr/include/xlocale.h
./testhandler.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/limits.h
./testhandler.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stdarg.h
./testhandler.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
./testhandler.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/syslimits.h
./util_funcs.o: mibdefs.h struct.h ucd-snmp/errormib.h /usr/include/alloca.h
./util_funcs.o: /usr/include/asm/errno.h /usr/include/asm/sigcontext.h
./util_funcs.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
./util_funcs.o: /usr/include/bits/byteswap.h /usr/include/bits/confname.h
./util_funcs.o: /usr/include/bits/endian.h /usr/include/bits/environments.h
./util_funcs.o: /usr/include/bits/errno.h /usr/include/bits/fcntl.h
./util_funcs.o: /usr/include/bits/in.h /usr/include/bits/local_lim.h
./util_funcs.o: /usr/include/bits/posix1_lim.h /usr/include/bits/posix2_lim.h
./util_funcs.o: /usr/include/bits/posix_opt.h /usr/include/bits/pthreadtypes.h
./util_funcs.o: /usr/include/bits/resource.h /usr/include/bits/sched.h
./util_funcs.o: /usr/include/bits/select.h /usr/include/bits/sigaction.h
./util_funcs.o: /usr/include/bits/sigcontext.h /usr/include/bits/siginfo.h
./util_funcs.o: /usr/include/bits/signum.h /usr/include/bits/sigset.h
./util_funcs.o: /usr/include/bits/sigstack.h /usr/include/bits/sigthread.h
./util_funcs.o: /usr/include/bits/sockaddr.h /usr/include/bits/socket.h
./util_funcs.o: /usr/include/bits/stat.h /usr/include/bits/stdio_lim.h
./util_funcs.o: /usr/include/bits/time.h /usr/include/bits/types.h
./util_funcs.o: /usr/include/bits/uio.h /usr/include/bits/waitflags.h
./util_funcs.o: /usr/include/bits/waitstatus.h /usr/include/bits/wchar.h
./util_funcs.o: /usr/include/bits/wordsize.h /usr/include/bits/xopen_lim.h
./util_funcs.o: /usr/include/ctype.h /usr/include/endian.h
./util_funcs.o: /usr/include/errno.h /usr/include/fcntl.h
./util_funcs.o: /usr/include/features.h /usr/include/_G_config.h
./util_funcs.o: /usr/include/gconv.h /usr/include/getopt.h
./util_funcs.o: /usr/include/gnu/stubs.h /usr/include/libio.h
./util_funcs.o: /usr/include/limits.h /usr/include/linux/errno.h
./util_funcs.o: /usr/include/linux/limits.h /usr/include/malloc.h
./util_funcs.o: /usr/include/netinet/in.h /usr/include/signal.h
./util_funcs.o: /usr/include/stdint.h /usr/include/stdio.h
./util_funcs.o: /usr/include/stdlib.h /usr/include/string.h
./util_funcs.o: /usr/include/sys/cdefs.h /usr/include/syslog.h
./util_funcs.o: /usr/include/sys/resource.h /usr/include/sys/select.h
./util_funcs.o: /usr/include/sys/socket.h /usr/include/sys/stat.h
./util_funcs.o: /usr/include/sys/syslog.h /usr/include/sys/sysmacros.h
./util_funcs.o: /usr/include/sys/time.h /usr/include/sys/types.h
./util_funcs.o: /usr/include/sys/ucontext.h /usr/include/sys/uio.h
./util_funcs.o: /usr/include/sys/un.h /usr/include/sys/wait.h
./util_funcs.o: /usr/include/time.h /usr/include/ucontext.h
./util_funcs.o: /usr/include/unistd.h /usr/include/wchar.h
./util_funcs.o: /usr/include/xlocale.h
./util_funcs.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/limits.h
./util_funcs.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stdarg.h
./util_funcs.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/stddef.h
./util_funcs.o: /usr/lib/gcc-lib/i386-redhat-linux/2.96/include/syslimits.h
./util_funcs.o: util_funcs.c util_funcs.h
