#!/bin/sh

case "$1" in
  Ext*) ;;
  *) exit 0 ;;
esac

VERSION=`echo $1 | sed 's/Ext-*//g;s/-/./g;'`

if [ $2 = "add" ]; then
#  cd agent/extensible/	
  perl -p -i.bak -e 's/VersionInfo="(.*)"/VersionInfo="'$VERSION'"/;' versioninfo.c ../../bug-report
  perl -p -i.bak -e 's#^s/VERSIONINFO/.*#s/VERSIONINFO/'$VERSION'/g#;' ../../sedscript.in
  cvs commit -m "version tag ( $VERSION )" versioninfo.c ../../sedscript.in ../../bug-report
fi

exit 0
