#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv1 get of system.sysUpTime.0

#
# Begin test
#

# standard V1 configuration: testcomunnity
. ./Sv1config

STARTAGENT

CAPTURE "snmpget $SNMP_FLAGS -v 1 localhost testcommunity system.sysUpTime.0"

STOPAGENT

CHECK "system.sysUpTime.0 = Timeticks:"

FINISHED
