#!/bin/sh

#
# test snmpv1 get support by reading a variable
#

. ../eval_tools.sh

HEADER for failure of SNMPv1 get with wrong community

#
# Begin test
#

# standard V1 configuration: testcomunnity
. ./Sv1config

STARTAGENT

CAPTURE "snmpget -On $SNMP_FLAGS -c notavalidcommunity -v 1 udp:localhost:$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.3.0"

STOPAGENT

CHECK "Timeout"

FINISHED
