#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv1 get of system.sysUpTime.1

#
# Begin test
#

# standard V1 configuration: testcomunnity
. ./Sv1config

STARTAGENT

CAPTURE "snmpget -On $SNMP_FLAGS -c testcommunity -v 1 udp:localhost:$SNMP_SNMPD_PORT .1.3.6.1.2.1.1.3.1"

STOPAGENT

CHECK "Error in packet"

FINISHED
