#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv2c get of system.sysUpTime.0

#
# Begin test
#

# standard V2C configuration: testcomunnity
. ./Sv2cconfig

STARTAGENT

CAPTURE "snmpget $SNMP_FLAGS -v 2c localhost testcommunity system.sysUpTime.0"

STOPAGENT

CHECK "system.sysUpTime.0 = Timeticks:"

FINISHED
