#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv2c getnext of system.sysUpTime

#
# Begin test
#

# standard V2C configuration: testcomunnity
. ./Sv2cconfig

STARTAGENT

CAPTURE "snmpgetnext $SNMP_FLAGS -v 2c localhost testcommunity system.sysUpTime"

STOPAGENT

CHECK "system.sysUpTime.0 = Timeticks:"

FINISHED
