#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv2c getnext of system.sysUpTime

#
# Begin test
#

# standard V2C configuration: testcomunnity
. ./Sv2cconfig

STARTAGENT

CAPTURE "snmpgetnext -On $SNMP_FLAGS -v 2c localhost testcommunity .1.3.6.1.2.1.1.3"

STOPAGENT

CHECK ".1.3.6.1.2.1.1.3.0 = Timeticks:"

FINISHED
