#!/bin/sh

#
# test snmpv2c get support by reading a variable
#

. ../eval_tools.sh

HEADER for failure of SNMPv2c get with wrong community

#
# Begin test
#

# standard V2C configuration: testcomunnity
. ./Sv2cconfig

STARTAGENT

CAPTURE "snmpget $SNMP_FLAGS -v 2c localhost notavalidcommunity system.sysUpTime.0"

STOPAGENT

CHECK "Timeout"

FINISHED
