#!/bin/sh

#
# test snmpv2c get support by reading a variable
#

. ../eval_tools.sh

HEADER for failure of SNMPv2c get with wrong community

#
# Begin test
#

# standard V2C configuration: testcomunnity
. ./Sv2cconfig

STARTAGENT

CAPTURE "snmpget -On $SNMP_FLAGS -v 2c localhost notavalidcommunity .1.3.6.1.2.1.1.3.0"

STOPAGENT

CHECK "Timeout"

FINISHED
