#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv3 getnext using initial of system.sysUpTime.0

#
# Begin test
#

# configure the agent to accept user initial with noAuthNoPriv
CONFIGAGENT rwUser initial
CONFIGAGENT createUser initial MD5 initial_PASS DES final_pass
CONFIGAGENT group   testinitialgroup  usm     initial
CONFIGAGENT view    all     included .1 80
CONFIGAGENT 'access  testinitialgroup  "" any noauth exact all all all'

STARTAGENT

CAPTURE "snmpgetnext $SNMP_FLAGS -v 3 -l nanp -u initial -n xxx localhost system.sysUpTime"

STOPAGENT

CHECK "system.sysUpTime.0 = Timeticks:"

FINISHED
