#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv3 get using initial/MD5DES of system.sysUpTime.0

SKIPIFNOT USE_OPENSSL

#
# Begin test
#

# standard V3 configuration for initial user
. ./Sv3DESconfig

STARTAGENT

CAPTURE "snmpget $SNMP_FLAGS -v 3 -x DES -X initial_test_pass_priv -a MD5 -A initial_test_pass_auth -l ap -u initial -n xxx localhost system.sysUpTime.0"

STOPAGENT

CHECK "system.sysUpTime.0 = Timeticks:"

FINISHED
