#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv3 get using templateSHA/SHA of system.sysUpTime.0

SKIPIFNOT USE_OPENSSL

#
# Begin test
#

# standard V3 configuration for templateSHA user
. ./Sv3configsha

STARTAGENT

CAPTURE "snmpget $SNMP_FLAGS -v 3 -a SHA -A initial_test_pass_auth -l anp -u initial -n xxx localhost system.sysUpTime.0"

STOPAGENT

CHECK "system.sysUpTime.0 = Timeticks:"

FINISHED
