#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv3 get using templateSHA/MD5DES of system.sysUpTime.0

SKIPIFNOT USE_OPENSSL

#
# Begin test
#

# standard V3 configuration for templateSHA user
. ./Sv3SHADESconfig

STARTAGENT

CAPTURE "snmpget $SNMP_FLAGS -v 3 -x DES -X initial_test_pass_priv -a SHA -A initial_test_pass_auth -l ap -u initial -n xxx localhost system.sysUpTime.0"

STOPAGENT

CHECK "system.sysUpTime.0 = Timeticks:"

FINISHED
