#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv3 user creation and usage using snmpusm

#
# Begin test
#

# standard V3 configuration for initial user
. ./Sv3config

STARTAGENT

CAPTURE "snmpusm $SNMP_FLAGS -v 3 -a MD5 -A initial_test_pass_auth -l anp -u initial -n xxx localhost create newtestuser templateMD5"
CAPTURE "snmpusm $SNMP_FLAGS -v 3 -a MD5 -A templateMD5_test_pass_auth -l anp -u newtestuser -n xxx -Ca localhost passwd templateMD5_test_pass_auth newtestpass"
CAPTURE "snmpget -On $SNMP_FLAGS -v 3 -a MD5 -A newtestpass -l anp -u newtestuser -n xxx localhost .1.3.6.1.2.1.1.3.0"

STOPAGENT

CHECK ".1.3.6.1.2.1.1.3.0 = Timeticks:"

FINISHED
