#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv3 snmptrapd USM user management with snmpusm

SKIPIFNOT USING_AGENTX_MASTER_MODULE
SKIPIFNOT USING_AGENTX_SUBAGENT_MODULE
SKIPIFNOT USING_SNMPV3_USMUSER_MODULE
SKIPIF SNMPTRAPD_DISABLE_AGENTX
SKIPIFNOT USE_OPENSSL

#
# Begin test
#

# configure AgentX socket
if [ "x$SNMP_TRANSPORT_SPEC" = "xunix" ]; then
  AGENT_FLAGS="$AGENT_FLAGS -x $SNMP_TMPDIR/agentx_socket"
  TRAPD_FLAGS="$TRAPD_FLAGS -x $SNMP_TMPDIR/agentx_socket"
else
  # XXX: try different ports if 7676/tcp is busy -- Bug 1335767
  AGENT_FLAGS="$AGENT_FLAGS -x tcp:${SNMP_TEST_DEST}7676"
  TRAPD_FLAGS="$TRAPD_FLAGS -x tcp:${SNMP_TEST_DEST}7676"
fi

# standard V3 agent configuration for initial user
. ./Sv3config

# configure agent as AgentX master
CONFIGAGENT master agentx

# Start the master agent
STARTAGENT

# XXX: move to TESTCONF.sh?
TRAPD_ENGINEID=0x0x80001f88802b3d0e06bbdf4e43
SNMPUSM_TRAPD_CONTEXT_ARGS="-n snmptrapd -CE $TRAPD_ENGINEID"

# configure snmptrapd
CONFIGTRAPD [snmp] persistentDir $SNMP_TMP_PERSISTENTDIR
CONFIGTRAPD oldEngineID $TRAPD_ENGINEID
CONFIGTRAPD createUser trapd_initial $DEFAUTHTYPE trapd_initial_test_pass_auth $DEFPRIVTYPE
CONFIGTRAPD createUser trapd_template $DEFAUTHTYPE trapd_template_test_pass_auth $DEFPRIVTYPE
CONFIGTRAPD authuser log newtestuser authNoPriv

# start snmptrapd
STARTTRAPD

# delay to let it connect and register all MIBs
DELAY

## verify snmptrapd usmUserTable management

# create vanilla user
CAPTURE "snmpusm $SNMP_FLAGS $AUTHTESTARGS $SNMPUSM_TRAPD_CONTEXT_ARGS $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPD_PORT create newtestuser_vanilla"
CHECKORDIE "User successfully created"

# clone template user
CAPTURE "snmpusm $SNMP_FLAGS $AUTHTESTARGS $SNMPUSM_TRAPD_CONTEXT_ARGS $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPD_PORT create newtestuser trapd_template"
CHECKORDIE "User successfully created"

# change auth passphrase of new user
CAPTURE "snmpusm $SNMP_FLAGS $AUTHTESTARGS -Ca $SNMPUSM_TRAPD_CONTEXT_ARGS $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPD_PORT passwd template_test_pass_auth newtestpass newtestuser"
CHECKORDIE "SNMPv3 Key(s) successfully changed"

# change priv passphrase of new user
CAPTURE "snmpusm $SNMP_FLAGS $PRIVTESTARGS -Cx $SNMPUSM_TRAPD_CONTEXT_ARGS $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPD_PORT passwd template_test_pass_auth newtestpass newtestuser"
CHECKORDIE "SNMPv3 Key(s) successfully changed"

# XXX: change key(s) directly?

## make use of new user (receive INFORMs)

# anp
#CAPTURE "snmptrap -Ci -d -v 3 -u newtestuser -l anp -a $DEFAUTHTYPE -A newtestpass $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPTRAPD_PORT 0 .1.3.6.1.6.3.1.1.5.1 system.sysContact.0 s received_inform_anp"
#DELAY
#CHECKTRAPDORDIE "received_inform_anp"

# ap
#CAPTURE "snmptrap -Ci -d -v 3 -u newtestuser -l ap -a $DEFAUTHTYPE -A newtestpass -x $DEFPRIVTYPE -X newtestpass $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPTRAPD_PORT 0 .1.3.6.1.6.3.1.1.5.1 system.sysContact.0 s received_inform_ap"
#DELAY
#CHECKTRAPDORDIE "received_inform_ap"

## stop daemons and finish

STOPTRAPD
STOPAGENT
FINISHED
