#!/bin/sh

. ../eval_tools.sh

HEADER SNMPv2c traps received and sent by tools

#
# Begin test
#

STARTTRAPD

CAPTURE "snmptrap -d $SNMP_SNMPTRAPD_PORT -v 2c localhost testcommunity 0 .1.3.6.1.6.3.1.1.5.1 system.sysContact.0 s blah"

STOPTRAPD

CHECKTRAPD "coldStart"

FINISHED
