#!/bin/sh

. ../eval_tools.sh

HEADER 1st CPU on Solaris using HOST-RESOURCES

if [ `uname -s` = "SunOS" ]; then

    SKIPIFNOT USING_HOST_MODULE

#
# Begin test
#

# standard V1 configuration: testcomunnity
    . ./Sv1config

    STARTAGENT

# ask for the description of the first CPU in the system

    CAPTURE "snmpget -On $SNMP_FLAGS -c testcommunity -v 1 udp:localhost:$SNMP_SNMPD_PORT .1.3.6.1.2.1.25.3.2.1.3.768"

    CHECKORDIE "CPU"

    STOPAGENT
  
    FINISHED

else
 
    REMOVETESTDATA
    ECHO "SKIPPED\n"
    exit 0;
fi
