#!/bin/sh

. ../eval_tools.sh

HEADER first disk on Solaris using HOST-RESOURCES

if test `uname -s` != "SunOS" ; then
    # a bogus skip for !suns
    SKIPIFNOT XXXYYYZZZ
fi

SKIPIFNOT USING_HOST_MODULE

#
# Begin test
#

# standard V1 configuration: testcomunnity
. ./Sv1config

STARTAGENT

# ask the device type of the first disk on the system

CAPTURE "snmpget -On $SNMP_FLAGS -c testcommunity -v 1 udp:localhost:$SNMP_SNMPD_PORT .1.3.6.1.2.1.25.3.6.1.2.1536"

STOPAGENT

CHECKORDIE "^.1.3.6.1.2.1.25.3.6.1.2.1536 = INTEGER: hardDisk(3)$"

FINISHED
