#!/bin/sh

. ../eval_tools.sh

HEADER swap on Solaris using HOST-RESOURCES

if test `uname -s` != "SunOS" ; then
    # a bogus skip for !suns
    SKIPIFNOT XXXYYYZZZ
fi

SKIPIFNOT USING_HOST_MODULE

SKIPIF DISABLE_SNMPV2C

#
# Begin test
#

# standard V1 configuration: testcomunnity
. ./Sv1config

STARTAGENT

# ask for the description of the first CPU in the system

CAPTURE "snmpget -On $SNMP_FLAGS -c testcommunity -v 1 $SNMP_TRANSPORT_SPEC:$SNMP_TEST_DEST$SNMP_SNMPD_PORT .1.3.6.1.2.1.25.2.3.1.5.3"

STOPAGENT

CHECKORDIE "^.1.3.6.1.2.1.25.2.3.1.5.3 = INTEGER:"

FINISHED
