#!/bin/sh

. ../eval_tools.sh

HEADER "full snmpwalk (SNMPv2c) against agent (may take time)"

SKIPIF DISABLE_SNMPV2C

# make sure snmpwalk can be executed
SNMPWALK="${SNMP_UPDIR}/apps/snmpwalk"
[ -x "$SNMPWALK" ] || SKIP

snmp_version=v2c
. ./Sv2cconfig

#
# Begin test
#

# higher timeout/retry values for safety
TIMEOUT=10
RETRY=5

STARTAGENT

CAPTURE "$SNMPWALK $SNMP_FLAGS -$snmp_version -c testcommunity -t $TIMEOUT -r $RETRY -Cp -Ct $SNMP_TEST_DEST$SNMP_SNMPD_PORT .1"
CHECKORDIE "No more variables left in this MIB View"

STOPAGENT
FINISHED
