#!/bin/sh

. ../eval_tools.sh

HEADER Unix Transport

SKIPIFNOT USING_MIBII_SYSTEM_MIB_MODULE
SKIPIFNOT NETSNMP_TRANSPORT_UNIX_DOMAIN

#
# Begin test
#

SNMP_TRANSPORT_SPEC=unix
SNMP_TEST_DEST=${SNMP_TMPDIR}/testunixsocket

. ./Stransport

# cleanup
rm -f $SNMP_TEST_DEST
