name: Build and test on OpenBSD

on:
  push:
  pull_request:

jobs:
  openbsd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Run Net-SNMP tests on OpenBSD
        uses: vmactions/openbsd-vm@main
        with:
          release: "7.9"
          usesh: true
          prepare: |
            rdate -n pool.ntp.org || true
            pkg_add bash
            bash -c "export MODE=regular && ci/install.sh"

          run: bash -c "export MODE=regular && ci/build.sh && ci/test.sh"
